### ISSUE TITLE
Typing of white-space

### ISSUE THREAD

**Issue by e11en** [emotion-js/emotion#1025]
- `emotion` version: 9.2.4
- `react` version: 16.4.0
- `react-emotion` version: 9.2.4

When using a mixin to fill my styled component the variable needs to be `whitespace` (lower case S) while in the normal use of white-space I need to use `whiteSpace` (upper case S). I was banging my head for a while trying to fix the error it produced. I think the typing somewhere needs to be fixed.

```javascript
export const nowrap = {
  whitespace: 'nowrap'
};

// With use of mixin
const Container = styled('div')(({theme}: {theme: Theme}) => ({
     ...nowrap
}));

// Normal use without mixin
const Container = styled('div')(({theme}: {theme: Theme}) => ({
     whiteSpace: 'nowrap'
}));

export const StyledDiv = compose<any, any>(
  withTheme()
)(Container);
````

**Comment by e11en** [comment]
Typescript

**Comment by Ailrun** [comment]
Then it's because you didn't put exact type.
`whiteSpace` accepts some specific strings only, where TS infer `{ whiteSpace string }` for your use case. Giving appropriate type will fix this.

**Comment by Ailrun** [comment]
@e11en `whitespace` works since typing should accept **any** key since there is something like `& > &`, `& > span`, ... and so on.
If my previous comment is not understandable to you, just check following example TS code.
https://www.typescriptlang.org/play/index.html#src=type%20ValidCSS%20%3D%20%7B%0D%0A%20%20%20%20%2F**%20There%20are%20many%20other%20values%2C%20but%20I%20omitted%20others%20for%20simplicity.%20*%2F%0D%0A%20%20%20%20whiteSpace%3A%20'nowrap'%20%7C%20'normal'%3B%0D%0A%20%20%20%20%2F**%20Of%20course%20emotion%20does%20not%20use%20%60any%60.%20Following%20is%20just%20for%20simplicity.%20*%2F%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20any%3B%0D%0A%7D%3B%0D%0A%0D%0Adeclare%20const%20emotionFun%3A%20(css%3A%20ValidCSS)%20%3D%3E%20void%20%0D%0A%0D%0Aconst%20yourStyle%20%3D%20%7B%0D%0A%20%20%20%20whiteSpace%3A%20'nowrap'%2C%0D%0A%7D%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20Following%20does%20not%20work!%0D%0A%20*%2F%0D%0AemotionFun(yourStyle)%3B%0D%0A%0D%0Aconst%20validTSStyle%3A%20ValidCSS%20%3D%20%7B%0D%0A%20%20%20%20whiteSpace%3A%20'nowrap'%2C%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Following%20does%20work!%0D%0A%20*%2F%0D%0AemotionFun(validTSStyle)%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20This%20is%20because%20of%20type%20inference%20system%20of%20TS.%0D%0A%20*%20It%20does%20not%20give%20any%20%0D%0A%20*%2F

**Comment by Ailrun** [comment]
https://github.com/Microsoft/TypeScript/pull/29510
This TS feature will help you to solve this issue in an easier way.

**Comment by Andarist** [comment]
As described - to fix the issue you need to use const assertions to narrow down the type from string to a concrete string. This is not an issue specific to emotion itself - it's just a TS stuff.
