### ISSUE TITLE
Themes cant be overridden - Component innerProp overrides the Context theme 

### ISSUE THREAD

**Issue by sesteva** [emotion-js/emotion#1055]
- `emotion` version: 10.0.0
- `react` version: 16.5.2

Relevant code.

```javascript
const StyledButton = styled(Button)`
  ${({theme}) => ({
    color: theme.colors.primary
  })};
`

StyledButton.defaultProps = {
  theme: {
    colors: {
      primary: 'red'
    }
  }  
}


export default StyledButton


const spark = {
  colors: {
    primary: 'green'
  }
}

export let Example = () => 
  <ThemeProvider theme={spark}>
    <Button>Cool cool cool</Button>
  </ThemeProvider>
```

What you did:

Applied ThemeProvider passing a theme to be applied by a comoponent from props.

What happened:

If the Styled component has static defaultProps OR if the expression provides a defaultValue for the prop, the theme passed via Context is lost/overriden.

Reproduction:

https://codesandbox.io/s/xoqklyknw

**Comment by sesteva** [comment]
I was looking at the code on and tests on ThemeProvider. It looks like the merge strategy when having nested theme providers is also showing the same effect where the props closer to the implementation are the ones overriding the ones coming from the further out Owner/ThemeProvider.

Looking at the tests it shows how the first snapshot the winning color is white and on the nested themes the padding is 8. On both occasions, the top parent lost on the merge strategy. This means we cant override parts of the theme.

I believe the same is evidence on my example above where defaultProps are overriding anything it comes from outside.

https://github.com/emotion-js/emotion/blob/6cb8d15438b01b8623af42f304d5ea3032332187/packages/emotion-theming/__tests__/__snapshots__/theme-provider.js.snap

**Comment by Andarist** [comment]
So it seems that in emotion@10 props.theme takes precedence over context theme, which makes sense. 

However `defaultProps` becomes `props.theme` and thus its *always* taking precedence over context theme. Which might be unexpected here - maybe we should inspect `tag.defaultProps.theme` and check props.theme against it to see if it comes from defaults or from actual props? And differentiate the behaviour based on that ofc.

The default theme merging strategy which you are mentioning ( https://github.com/emotion-js/emotion/blob/d3d522dadbb58a5170bafe21615da19f675e43e4/packages/emotion-theming/src/theme-provider.js#L30 ) should not change - it's important for the theme to win over outerTheme, but it also is irrelevant to your problem as it only kicks in for nested ThemeProviders and you dont use such pattern in your example

**Comment by Andarist** [comment]
> Hi @Andarist, thank you for taking a look at this. Could you point me to where in the code should the change/fix be applied? is it on styled? I could find some time to create a PR.

`@emotion/styled-base`. This issue is kinda tricky though so probably it would be good to wait for @mitchellhamilton comment to see what he thinks about it. You could also ditch relaying on `defaultProps` for providing a default theme for a component and instead default in your interpolation like this:
```js
const StyledButton = styled(Button)`
  ${({theme}) => ({
    color: (theme.colors && theme.colors.primary) || 'red',
  })};
`
```
I understand that this is not very ergonomic though.

> On the second part....now you got me thinking and curious why should the innnerTheme win.

As mentioned - this is separate issue than what you are experiencing here. However the `innerTheme` should win because it allows for shadowing themes with nested ThemeProviders, you can make a top level provider and wrap some part of your app with other ThemeProvider making this very subtree styled differently. With different merging strategy that would not be possible.

It also corresponds to how React context work - you always shadow the value from outer provider and this works the same, it only doesnt shadow whole value but rather merge outer with inner theme (which shadows theme properties).

**Comment by Andarist** [comment]
`.defaultProps` will be most likely deprecated by the React team in the future, so we don't put any support for this into emotion. 

We believe that theming doesn't even belong to emotion - because a single theme has numerous problems associated with it. See reasoning in https://github.com/emotion-js/emotion/pull/1577 . I believe this is what you should be ultimately doing if you want to provide a default for a theme (because you can just embed it inside a context you create).

However - for the time being, we are going to support the theme in the core, because it's what people expect. I've prepared a PR (https://github.com/emotion-js/emotion/pull/973) with a helper to create themes - so it will be easier to do that in the future, for now, you can just use custom context with a simple hook.
