### ISSUE TITLE
Doc needs to clarify if CSS prop are recreated on every render pass

### ISSUE THREAD

**Issue by desmap** [emotion-js/emotion#1117]
CSS props are the way to create efficient style without naming fatigue. Since I do this extensively, I need to know if there are any downsides. The styled-components docs suggest not to declare anything within the render method [Define Styled Components outside of the render method](https://www.styled-components.com/docs/basics#define-styled-components-outside-of-the-render-method). So, how is it now with emotion's CSS prop? Are they recreated with every render and is it better to declare them outside but then again paired with naming fatigue.

**Comment by Andarist** [comment]
Emotion is using heavy caching under the hood - you can safely use `css` in your render methods.

**Comment by desmap** [comment]
This sounds awesome we should put it in the docs and stress this caching feature. I mean, CSS props work out of the box without any config mess and are cached.

**Comment by Andarist** [comment]
Happy to accept a PR for this 😉

**Comment by tkh44** [comment]
It is ill-advised to create styled components in render because it creates a component.

The `css` prop is more like a function call that computes the string value of the `className` prop. If the styles are the same, each call will return the same value and the dom attr doesn't change. Furthermore, if emotion has seen this style before it shortcuts and returns the previously computed className.

**Comment by kelly-tock** [comment]
was this ever added to the docs?  the examples seem to suggest it's all good, but a literal callout would be nice
