### ISSUE TITLE
Duplicated css attribute

### ISSUE THREAD

**Issue by kossel** [emotion-js/emotion#1162]
- `emotion` version: 9.2.12
- `react` version:  16.5.2

**Relevant code:**

```javascript
import React from "react";
import ReactDOM from "react-dom";
import styled from "react-emotion";
import "./styles.css";

function App() {
  const a = {
    x: props => {
      return { color: "red" };
    },
    y: props => {
      return { color: "blue" };
    }
  };
  const H1 = styled("h1")(a.x, a.y);
  return (
    <div className="App">
      <H1 color="lightgreen"> Hello </H1>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```

**What you did:**
I use same css attributes in  different render function

**What happened:**
In my project it outputs duplicate attributes, but not in the emotion website, for example go to https://5bb1495273f2cf57a2cf39cc--emotion.netlify.com/docs/styled#object-styles, and put the same code, you will see only one `color` attribute , is there a way to achieve that?

![image](https://user-images.githubusercontent.com/1760498/50856012-312eb700-134f-11e9-8f08-3f7f84a94cd0.png)

**Reproduction:**
https://codesandbox.io/s/321jlw7wk6

**Comment by Werter12** [comment]
In your example you passing two functions with static `color`. I think you should pass `color` via `props`.
``` 
const a = {
   x: props => {
      return { color: props.color };
    },
  };

  const H1 = styled("h1")(a.x);

  <H1 color="red"> Hello </H1>
  <H1 color="blue"> Hello 1</H1>
```

**Comment by kossel** [comment]
Thanks for the reply, the static color is just mean as an example to show case the 2 functions returning the same attribute will render duplicated css while in the docs not.

The real scenario maybe more complex for example func1 would be return style for varian1 button, and func2 would return variant2 button, and some css attribute may collide

**Comment by tkh44** [comment]
This is intentional. The styles are written to the CSSOM in the order emotion "sees" them. We leverage the CSS specification in order to ensure predictable composition and remove any unnecessary overhead of the library doing the dedupe work. You can see this for yourself if you switch around `a.x` and `a.y` in your `styled` call. Whatever is last "wins" and is the color the element receives.


The reason it's not seen on the sandbox or netlify deploy is that those are production builds that do not write the styles to the DOM (for debugging and general DX) but rather the CSSOM directly for performance. For more information on the CSSOM used for production versions, check out this article: https://medium.com/@tkh44/writing-a-css-in-js-library-from-scratch-96cd23a017b4
