### ISSUE TITLE
missing displayName after using css-prop

### ISSUE THREAD

**Issue by machiaveli88** [emotion-js/emotion#1173]
hey there, I've got a problem with missing displayName while using css-prop:

`<SideBar><SideBarPanel css={{ border: '1px solid red' }}>Test</SideBarPanel></SideBar>`

 If I use the code above, type.displayName (see code below, called by SideBar) will be `undefined` instead of `SideBarPanel`. Is this an error or am I doing something wrong?

`Children.map(children, ({ type }) => {
console.log(type.displayName);
})`

Thanks for your help!

**Comment by Andarist** [comment]
This happens because with `jsx` pragma we actually don't render your component directly, but rather our own which later renders the one you have given us. This **might** get "fixed" in upcoming emotion@11 (I'm going through all issues to plan the work for it) - this is not yet guaranteed, but likely. Keep in mind though that we believe that you really shouldn't base your runtime logic based on the `.displayName` property - it's supposed to be only helpful for debugging via React DevTools. Closing this as it's not something we want to "fix" on purpose, just something that might get done in the future as side-effect of refactoring. Hope you understand.

**Comment by ehansen-jl** [comment]
Using the display name will allow for the best support in a HOC (one that manages position and spacing for example). If we should use a different name, we would still need emotion to carry over custom variables attached to the component (`const myComp = () => {}; myComp.customName = 'myComp';`

**Comment by ehansen-jl** [comment]
Found out there's a `props.__EMOTION_TYPE_PLEASE_DO_NOT_USE__?.displayName`

**Comment by alfnielsen** [comment]
Hi, Can someone point at the issue for fixing this ?
(Or some discussion on it, I will like to write the fix if no one else wont) 

It's a problem for Library building where we need to make things like analytics on children, but more important to enable children aware changes (Aka runtime virtual dom manipulation before final react render)

So we need to know (in runtime, before final React render) which children and their types are in a parent component.

(This is something that React enables and it has methods like the cloneElement for it, but the removal of information thats done here in Emotion, prevent that)

Thanks

**Comment by alfnielsen** [comment]
@Andarist 

Where do you find such a recommendation ?

On the official documentation "Transforming elements" are liste just like any other feature (3 area in the overview ) - with no warning or recommendation not to use:

https://reactjs.org/docs/react-api.html

**Comment by Andarist** [comment]
From various comments of the React team members that were made on GitHub and on Twitter. Most importantly such things break composition capabilities:
```js
function Button({ ...props }) { return <button/> }
function MyButton({ ...props }) { return <Button type="button" {...props} /> }
function ButtonGroup() { /* I will try to introspect Button children */ }

// oops, we can't really recognize MyButton as being just a wrapper around Button
<ButtonGroup><MyButton>{'Click'}</MyButton></ButtonGroup> 
```

**Comment by alfnielsen** [comment]
Well your ButtonGroup dont have any Button (it has a MyButton), this doesn't break anything, it's just an incorrect analytic to think it has a Button.
Many libraries use the knowledge that the ButtonGroup has a MyButton and it will break the composition if you force the libraries to use properties instead of list of children.

I don't undestand why Emotion, will force anything other then Style (css), it's a great tool for doing css-in-js, but it's role is not to have a concern on virtual dom and how it's used, that is a concern for the virtual dom library like React or Vue etc..

It seems like an active choice to remove accessibility to the properties user has added themself ? 

If React would prevent this (for whatever reason) they would not have it in the main feature overview,
and I agree that if you not building libraries you should likely avoid this,
but emotion it self (as a Library) do things that is not recommended in normal code, like the "__EMTION_TYPE_PLEASE_TO_NOT_USE_" which other libraries (that does use React's tranformation features) are forced to used, just to use a well document React feature.
