### ISSUE TITLE
Export cx from `@emotion/core`

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1225]
Hi, would you accept a PR that makes `cx` a top level export from @emotion/core?

Right now to use it you have to either use `<ClassName>` or the `emotion` package.

**Comment by Andarist** [comment]
It's not a good idea within current design, because `cx` is **eager** whereas `css` from `@emotion/core` core is **lazy-ish** (it constructs an object, it doesnt insert the styles to the DOM, it also **doesnt** produce final class name - this happens in `jsx`). 

`cx` just cant combine regular classes with `css` output outside of the render functions.

**Comment by FezVrasta** [comment]
Thanks for the answer, does it mean that the `cx` exposed by `emotion` is different from the one of `ClassNames`?

**Comment by Andarist** [comment]
Yes.
https://github.com/emotion-js/emotion/blob/554a29d14aa7609601a82e6cbb20a8b73177feb9/packages/core/src/class-names.js#L106-L111
https://github.com/emotion-js/emotion/blob/554a29d14aa7609601a82e6cbb20a8b73177feb9/packages/create-emotion/src/index.js#L104-L106

**Comment by FezVrasta** [comment]
Oh ok I see, it makes sense then. Sorry for the waste of time!

**Comment by Eastonium** [comment]
I'm currently trying to use vanilla emotion's `cx` as a direct replacement for the classnames library. I'm not using it on styles generated by emotion, just for strings + objects. Should I still switch to using the `cx` provided by the `ClassNames` component's render prop function? Honestly I'm hesitant because the `ClassNames` prop with its render function is awfully bulky and ugly.
