### ISSUE TITLE
renderToString does not extract css in jest

### ISSUE THREAD

**Issue by FreddieRidell** [emotion-js/emotion#1245]
- `emotion` version: `^10.0.7`
- `react` version: `^16.8.3`

**What you did:**

tried to stringify components and styles in a jest test

**What happened:**

only the components were stringified, styled were not.

**Reproduction:**
https://github.com/FreddieRidell/minimal-emotion-reproduction

**Problem description:**
When using `import { renderToString } from 'react-dom/server'` in a jest test, only the components are stringified, no css styles are included. When the same code is run outside of a jest context the styles are stringified correctly.

**Suggested solution:**
I'm not sure I'm afraid.

> ps. thanks for the great library, I'm a huge fan of the object syntax for styles!

**Comment by kylegach** [comment]
We ran into this, too. There's a [related conversation on the emotion Slack](https://emotion-slack.slack.com/archives/C64D9NR24/p1547067995031900) (you'll need to sign in to view it). Here's a screengrab:

<img width="969" alt="screenshot of Slack conversation" src="https://user-images.githubusercontent.com/486540/53433915-a82d1700-39b2-11e9-92b0-04cda0351566.png">

The TL;DR is that emotion differentiates between browser and server bundles, and styles are only output in `renderToString` in the server bundle. So you'd need to configure jest to run with a `node` target.

Ultimately, we ended up asserting on snapshots, which are properly serialized with [jest-emotion](https://emotion.sh/docs/jest-emotion), instead of using `renderToString`.

**Comment by FreddieRidell** [comment]
Thanks very much, I'll see if I can get jest to target node.

For context: I've been trying to make my own custom snapshotter that outputs valid html so that the snapshots can be completely viewed in a browser viewer. Is there any way you could think to do that?

If not I'll close this issue as resolve, thanks for your help! :)

**Comment by kylegach** [comment]
That's an interesting idea. I wouldn't know where to start beyond looking at the source of jest-emotion.
