### ISSUE TITLE
Source maps point to grandparent

### ISSUE THREAD

**Issue by esamattis** [emotion-js/emotion#1258]
- `emotion` version: 10.0.7
- `react` version: 16.8.3

**Relevant code:**

I tend to extend all my component from a react-native like View component:

```javascript
// View.js
export const View = styled.div`
    display: flex;
    position: relative;
    box-sizing: border-box;
    flex-direction: column;
`;
```

**What you did:**

Like

```js
// index.js
const Container = styled(View)`
    background-color: hotpink;
`;
```

**What happened:**

But for the `Container` component chrome style inspector points to the View.js.

![image](https://user-images.githubusercontent.com/225712/53877374-a9dd8700-4011-11e9-87c9-dcd0c76c2f15.png)

**Reproduction:**

	git clone https://github.com/epeli/emotion-source-map-bug.git
    cd emotion-source-map-bug
    npm ci
    npm start

Open <http://localhost:3000> and inspect the pink element

**Suggested solution:**

The source map should point to the child that was rendered. Current behaviour is not very useful with my usage as every component points to the View.js.

**Comment by Andarist** [comment]
I've confirmed that with v10 this incorrectly points to:
https://github.com/esamattis/emotion-source-map-bug/blob/f6d471c527818a6338526b91a8baeca0d2e62d37/components/View.js#L3

but with upcoming v11 it points to:
https://github.com/esamattis/emotion-source-map-bug/blob/f6d471c527818a6338526b91a8baeca0d2e62d37/pages/index.js#L5

Which I believe is what is the expected result here. So I'm going to close this as being fixed in the upcoming v11. Sorry that you had to wait so long for an answer, hope you understand.

**Comment by esamattis** [comment]
No worries, we're all busy and this is open source. Happy to see progress!
