### ISSUE TITLE
Non component equivalent of create-emotion-styled in emotion v10

### ISSUE THREAD

**Issue by sampotts** [emotion-js/emotion#1277]
- `emotion` version: 10.0.9
- `preact` version: 8.4.3

**Problem description:**
Previously in version < 10 it was possible to create a "proxy" method to create an export of emotion with the stylis plugins built-in. As this project is used to embed on third party websites, adding `!important` to all declarations is necessary so I created a plugin to do so. This required the use of `create-emotion-styled`. For example, I had two files:

create.js

```javascript
import createEmotion from 'create-emotion';
import { replaceAll } from '../utils/strings';

const context = typeof global !== 'undefined' ? global : {};

const disablePrefix = ['letter-spacing'];

export const {
    flush,
    hydrate,
    cx,
    merge,
    getRegisteredStyles,
    injectGlobal,
    keyframes,
    css,
    sheet,
    caches,
} = createEmotion(context, {
    // https://github.com/thysultan/stylis.js#plugins
    stylisPlugins: (context, content, selectors) => {
        const [selector] = selectors;

        if (selector && selector.endsWith('*')) {
            return content;
        }

        switch (context) {
            case 1:
                return `${content} !important`;

            case 3:
                if (selector === '@font-face' || (selector.startsWith('@') && selector.includes('keyframes'))) {
                    return replaceAll(content, ' !important');
                }

                return content;

            default:
                return content;
        }
    },
    key: 'embed',
    prefix: key => !disablePrefix.includes(key),
});
```

index.js

```javascript
import createEmotionStyled from 'create-emotion-styled';
import Preact from 'preact';
import * as emotion from './create';

export default createEmotionStyled(emotion, Preact);

export * from './create';
```

Then in a component, it was nice and clean... 

```javascript
import styled from '../emotion';

const Element = styled.img`
    vertical-align: middle;
    height: auto;
    max-width: 100%;
`;

const Image = props => <Element {...props} />;

export default Image;
```

I saw [this issue](https://github.com/emotion-js/emotion/issues/1064) but the solution doesn't address this issue for me unless I'm missing something obvious (apologies if so). From what I can see now I would have to wrap every component in an extra component to replicate the functionality that was possible prior to 10 as above. This means adding a wrapper component in a lot of places to get the same functionality. 

**Suggested solution:**

Perhaps restore the functionality of `create-emotion-styled` somehow?

**Comment by FezVrasta** [comment]
You don't need to wrap any component in `CacheProvider` you need to wrap your whole app (or relevant part) with it.

**Comment by sampotts** [comment]
That assumes I'm using React/Preact for the whole app. The use here is for embedded widgets on third party sites (hence needing to `!important` the styles) and we have quite a few of them. I guess I'll need add these `CacheProvider` wrappers into all of them then. Hopefully it works ok with Preact. I can't find much information about it whether it requires support for `Fragment` which is missing in the current stable version of Preact.

**Comment by Andarist** [comment]
Sorry for not getting to you back sooner - I hope you have resolved your issue. If not - let us know by creating a new issue. 

It seems that your use case is rather niche (I don't treat this issue lightly as I'm working on an embeddable widget myself) and I'm afraid we won't reintroduce `create-emotion-styled` functionality as CacheProvider is intended to replace the need for it entirely. I understand that this might be somewhat painful for you if you don't own a single root component on the host page and you cannot just wrap the entire thing in a single provider, but it is what it is. Technically you could kinda build this yourself with:
```js
const myCache = createCache();
const myStyled = Tag =>
  styled(props => (
    <CacheProvider value={myCache}>
      <Tag {...props} />
    </CacheProvider>
  ));
```

You'd probably have to fix up forwarded props with providing correct `shouldForwardProp` based on your `Tag`, but this is very doable.

This would cause each of your component acting as a provider which might get noisy in devtools and currently there is no easy workaround for this - but just because we don't use hooks internally yet. Once we migrate to hooks (hopefully soon-ish!) the output tree could be flattened with a simple trick of inspecting the context upfront and wrapping the rendered element with CacheProvider only conditionally (when context is empty).
