### ISSUE TITLE
Global component creates multiple internal stylesheets

### ISSUE THREAD

**Issue by dmbdesignpdx** [emotion-js/emotion#1291]
- `emotion` version: 10.0.7
- `react` version: 16.8.2

Hello, 

Either I am misunderstanding how the `Global` component works or it is not intended to do what I am assuming: which is that it creates a single internal stylesheet for the rules it is given through `styles`. That said, if it is the former, then please skip to my question at the bottom, otherwise...

**What you did:**
Tried to use the `Global` component to create a single internal stylesheet by importing a single source of rules. A snippet of my layout:
```javascript
import { Global } from '@emotion/core'
import globalStyles from '../styles/global'

...

const Layout = ({children}) => (
  <>
    <Global styles={globalStyles} />
    <SEO ... />
    {children}
  </>
)
```

**What happened:**
Every defined rule is getting its own `<style>`.

A snippet of the exported `globalStyles` that's being imported as the styles for `Global`:
```javascript
import { css } from '@emotion/core'

const globalStyles = css`
  @font-face { ... }
  html { ... }
  body { ... }
  a { ... }
`
```
Becomes:

```html
<head>
  <style>@font-face { ... }</style>
  <style>html { ... }</style>
  <style>body { ... }</style>
  <style>a { ... }</style>
</head>
```

**Problem description:**
Multiple stylesheets are being created for each defined rule, even if each rule resides in a single `css` object.

**If Skipped:**
If the `Global` component is not intended to do what I expected, that's fine, you may close this. But what I would really like to know then, is how did the Emotion website achieve a single internal stylesheet?

Also, there is the **high** possibility that I am just doing this completely wrong for what I want. If that's case, could I kindly get a nudge in the right direction?

Thank you.

**Comment by tkh44** [comment]
In development mode, we generate a style tag for each element so that you are able to edit the styles in the browser dev tools. The various browser dev tools do not let you edit styles inserted via CSSOM with the style editor in the elements panel.

The emotion website has a single style tag because it is running in production mode where we consolidate all of the styles and insert them via `insertRule` into a single stylesheet.

I don't believe you are doing anything wrong. You're probably just in development mode. If you build your site for production it should look like you expect.

**Comment by sqal** [comment]
Make sense. Thank you for your clarification :)

**Comment by dmbdesignpdx** [comment]
👍 Got it — thank you for clearing that up.
