### ISSUE TITLE
how to use `as` prop with generative props?

### ISSUE THREAD

**Issue by lifeiscontent** [emotion-js/emotion#1319]
Given this example which uses reach router to get the isPartiallyActive and isActive props to generate a new set of props how do I use emotion to pass the generative props to it?

https://spectrum.chat/emotion/help/how-do-i-use-the-as-prop-with-reach-router~27555f98-c021-4d5d-ad82-930b2d8511c9

**Comment by JoshRosenstein** [comment]
@lifeiscontent  I dont think you can achieve that based on what reach Router source looks like:

https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/index.js#L374-L385

Your essentially applying the styles to the Root `Link`, but your real target is its nested `anchor`, so emotion doesnt have access to Locations context yet (isCurrent, isPartiallyCurrent, href, location ).

So once the root gets styled the classname gets passed down to the anchor which is why you are available to style the root and why in your example you are getting red. 

So you have two options to achieve a dynamic style based on getProps
1. create a getProps that returns inline style. ie.
```js
const getProps = props => {
  console.log("getProps", props);
  return {
    style:{color: props.isPartiallyCurrent?"green" : "red"}
  };
};
```
(you can do this for just the dynamic portions of the styles and use emotion to style any static styles or dynamic ones that dont depend on Location props aka getProps )

2. Same method as above but using Global and attributes. (cant use classnames if you still want to style the root with emotion because[ getProps overwrites anchorProps](https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/index.js#L388-L389) ) ie
```js  

const getProps = ({isPartiallyCurrent}) => {
  return {
    'data-state':isPartiallyCurrent && 'PartiallyCurrent'
  }
};
const TestCase3 = props => (
  <StyledLink3  to="/" getProps={getProps}>
    Home
  </StyledLink3>
);
....
<div>
    <Global
      styles={{
        'a[data-state="PartiallyCurrent"]': {
          color: "green",
        }
      }}
    />
 <MYReachLink/>
 </div>
```
Originally I was thinking of creating Custom Link element where you would just replace the anchor with styled component but Reach Router exports everything you need except the [`BaseContext`.](  <BaseContext.Consumer>).

Hope this helped

**Comment by JoshRosenstein** [comment]
Hey sorry just thought a third option with some factories, where the limitations here is you can only style the children of Link based on getProps:

```js
import { Router, Link } from "@reach/router";
import styled from "@emotion/styled";

const StyledLinkText = styled.span(props => {
  return { color: props.isSelected ? "green" : "red" };
});

const getPropsFactory = label => props => {
  return {
    children: React.createElement(
      StyledLinkText,
      {
        isSelected: props.isPartiallyCurrent,
        isActive: props.isCurrent
      },
      label
    )
  };
};

const CreateLink = (to, label) => props => (
  <Link to={to} getProps={getPropsFactory(label)} />
);

const MyLink = CreateLink("/", "Link1");
const MyLink2 = CreateLink("dashboard", "Link2");

const App = ({ children }) => (
  <div>
    <Logo />
    <nav>
      <MyLink />
      <MyLink2 />
```

**Comment by lifeiscontent** [comment]
@JoshRosenstein wow, nice, thanks for your efforts, I ended up switching back to react-router-dom and using the Route component.
