### ISSUE TITLE
[Question]: How do you prevent css prop getting re-rendered in React? Do I have to use useMemo()?

### ISSUE THREAD

**Issue by rockmandash** [emotion-js/emotion#1349]
Sorry about that I ask the question that's more related to React, but I just want to know the best practice.

So the example:

```jsx
import { css, jsx } from '@emotion/core'

const color = 'darkgreen'

const otherProp = 'otherValue'

render(
  <div
    css={css`
      background-color: hotpink;
      &:hover {
        color: ${color};
      }
    `}
  >
    This has a hotpink background.
    {otherProp}
  </div>
)
```

So if the component gets re-rendered based on `otherProp` changed, will this function generating new-and-same result?

```jsx
css`
  background-color: hotpink;
  &:hover {
    color: ${color};
  }
`
```

I wonder if `css()` function has internal cache.

Otherwise, I will have to use `useMemo()` everytime for my css stylesheet if there are some unrelated `prop`.

Will it posiible for that `css` function has some kind of default cache?

Thank you!

**Comment by Andarist** [comment]
Basically `css` result is the same each time you call it with the same arguments conceptually, but not technically - because it's an object. 

I wouldn't be too concerned about perf though, optimize only bottlenecks - most of your components with styles are leaf nodes and it just doesn't matter for them if that generated object is the same or not.
