### ISSUE TITLE
Custom CacheProvider does not pick up styles from bundled components

### ISSUE THREAD

**Issue by ChrisMccollister-minted** [emotion-js/emotion#1386]
**Current behavior:**

A custom `CacheProvider` does not pick up styles from components imported from bundled JS. Styles for these components are prefixed with the default `css` key and are injected into the document head, not the location specified in the cache. 

**To reproduce:**

Repo with example: https://github.com/ChrisMccollister-minted/emotion-cache-provider-test

**Expected behavior:**

For the code shown below, I would expect the styles used by `LibraryComponent` to be prefixed with `bbb` and injected into the div holding the `t2Ref`.

```JavaScript
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import {css, CacheProvider} from '@emotion/core';
import createCache from '@emotion/cache';
import LibraryComponent from 'emotion-cache-test-lib';

const localStyle = css`
  color: red;
`;

const LocalComponent = ({children}) => (
  <div css={localStyle}>{children}</div>
);

class Main extends Component {
  constructor(props) {
    super(props);
    this.t1Ref = React.createRef();
    this.t2Ref = React.createRef();
    this.state = {
      isReady: false,
    };
  }

  componentDidMount() {
    this.t1Cache = createCache({
      key: 'aaa',
      container: this.t1Ref.current,
    });
    this.t2Cache = createCache({
      key: 'bbb',
      container: this.t2Ref.current,
    });
    this.setState({isReady: true});
  }

  render() {
    const {isReady} = this.state;
    return (
      <div>
        <div ref={this.t1Ref}>
          {isReady &&
            <CacheProvider value={this.t1Cache}>
              <LocalComponent>
                LocalComponent
              </LocalComponent>
            </CacheProvider>
          }
        </div>
        <div ref={this.t2Ref}>
          {isReady &&
            <CacheProvider value={this.t2Cache}>
              <LibraryComponent>
                LibraryComponent
              </LibraryComponent>
            </CacheProvider>
          }
        </div>
      </div>
    );
  }
}

ReactDOM.render(
  <Main />,
  document.getElementById('root')
);
```

Looking at the resulting document, I see that the styles for `LocalComponent` are correctly prefixed with `aaa` and injected into the div holding the `t1Ref`. The styles used by `LibraryComponent` however, are prefixed with the default `css` prefix and injected into the document head, as if no custom `CacheProvider` was being used.

<img width="552" alt="Screen Shot 2019-06-04 at 3 43 35 PM" src="https://user-images.githubusercontent.com/20825581/58914836-26513600-86e5-11e9-8036-feb9dc80d269.png">

If this is the intended behavior, then I would expect the docs to mention that `CacheProvider` does not work with bundled components.

**Environment information:**

- `react` version: `16.8.6`
- `@emotion/core` version: `10.0.10`
- `@emotion/cache` version: `10.0.9`

**Comment by Andarist** [comment]
Can you reproduce this when installing LibraryComponent? I mean - when not using npm link?

I think the problem is that each project - a library and your app - has its own `@emotion/core` installed, so they actually have 2 different contexts (referentially speaking). This might happen when using npm link.

**Comment by ChrisMccollister-minted** [comment]
Yes, I can reproduce this when I'm installing the package instead of using link.

**Comment by FezVrasta** [comment]
@andarist could we put three context into some global space to avoid this issue? I know is not going to be nice, but maybe just for dev builds we could put it into window.__EMOTION10_CONTEXT__

**Comment by Andarist** [comment]
> Edit: After further testing, I can get this to work as expected in my test repo if I'm not using yarn link. I'm still seeing issues with other bundles but I'm guessing that's due to a different configuration issue causing the same duplicate context situation.

That has to be it. You can try to find the culprits and resolve your dependency ranges in such a way that u would have a single version of emotion@10 in your node_modules. If you are using webpack I would advise aliasing it (and other shared react libs and react itself) to resolved paths. I'm doing this it with something like this:
```
const dependencies = Object.keys(require(nodePath.join(findPkgRoot(__dirname), 'package.json')).dependencies)

const forcedNodeModules = dependencies..reduce((acc, dep) => {
  acc[dep] = findPkgRoot(require.resolve(dep))
  return acc
}, {})

module.exports = {
  // webpack config
  // ...
  resolve: {
    // ...
    alias: forcedNodeModules
  }
}
```

> @Andarist could we put the context into some global space to avoid this issue? I know is not going to be nice, but maybe just for dev builds we could put it into window.__EMOTION10_CONTEXT__

IMHO that wouldn't solve the issue completely and could introduce some bizarre bugs into somebody's setup. We can't assume how people differentiate their dev & prod builds, so any attempt to fix the dev one might just hide the issue and cause breakage accidentally in prod.

We could use this to produce a dev only warning though, that we have detected multiple instances of our package being loaded.

Keep in mind that the problem here is not unique to emotion itself, anything that relies on same references can break - i.e. `instanceof` checks are somewhat unreliable for that reason (when checking instanceof of something external). Also react itself "suffers" from it - bad things might happen when including multiple versions of react, especially when using hooks as they rely on shared scope inside of the react modules.

**Comment by FezVrasta** [comment]
A warning would be great!

**Comment by Andarist** [comment]
There is nothing that we can do to fix this - it's just how things work in general (the issue is not exclusive to emotion). We could introduce some kind of a warning - which is tracked here https://github.com/emotion-js/emotion/issues/1470 , but we need to think about all pros and cons of this before implementing this.

**Comment by zeckdude** [comment]
This works for JSS btw, so I'm not convinced this issue is how things work in general. I couldn't tell you what the solution is but they made it work. Basically I have some code in the shadow dom in which I am using components made in Material UI that are from an external package and I am able to specify the location where those styles should be inserted. Not only does it insert all styles that are created within the shadow dom but also the ones that are imported via the package.

```js
import root from 'react-shadow';
import { jssPreset, StylesProvider as MuiStylesProvider, MuiThemeProvider } from '@material-ui/core/styles';
import { ThemeProvider as EmotionThemeProvider } from 'emotion-theming';
import { create } from 'jss';
import React, { useState } from 'react';
import { ToucanTheme, ToucanComponents } from 'toucan-design';

import { CacheProvider as EmotionCacheProvider } from '@emotion/core';
import createCache from '@emotion/cache';

// Define custom location to insert JSS styles (instead of document head)
// From: https://stackoverflow.com/a/57221293/83916

// Define custom location to insert Emotion styles (instead of document head)
// From: https://emotion.sh/docs/cache-provider

const ToucanShadowDomContainer = ({ children }) => {
  const [jss, setJss] = useState(null);
  const [emotionCache, setEmotionCache] = useState(null);

  function setRefAndCreateJss(headRef) {
    if (headRef && !jss) {
      const createdJssWithRef = create({ ...jssPreset(), insertionPoint: headRef });
      setJss(createdJssWithRef);
    }
  }

  function setRefAndCreateEmotion(emotionRef) {
    if (emotionRef && !emotionCache) {
      const createdEmotionWithRef = createCache({
        container: emotionRef,
      });
      setEmotionCache(createdEmotionWithRef);
    }
  }

  function setShadowHeadRef(headRef) {
    setRefAndCreateJss(headRef);
    setRefAndCreateEmotion(headRef);
  }

  return (
    <root.div>
      <head ref={setShadowHeadRef} />
      {jss && emotionCache && (
        <MuiThemeProvider theme={ToucanTheme}>
          <EmotionThemeProvider theme={ToucanTheme}>
            <EmotionCacheProvider value={emotionCache}>
              <MuiStylesProvider jss={jss}>
                <ToucanComponents.ScopedCssBaseline>{children}</ToucanComponents.ScopedCssBaseline>
              </MuiStylesProvider>
            </EmotionCacheProvider>
          </EmotionThemeProvider>
        </MuiThemeProvider>
      )}
    </root.div>
  );
};

export default ToucanShadowDomContainer;

```

**Comment by Andarist** [comment]
The "double context" problem is literally the only way this can break. I would encourage you to check your node_modules for multiple `@emotion/core` packages.

**Comment by zeckdude** [comment]
@Andarist If that is the case, how would I solve the multiple packages issue?

**Comment by glomotion** [comment]
I wonder, could someone help me, i'm finding the same problem. 

I have a design system lib which uses `@emotion/css`. 

Im consuming said design system from this repo: 
https://github.com/glomotion/test-emotion-cypress-7-x

Im trying to have the `@emotion/css` styles generated inside the DS - injected into the document.body, instead of the document.head. Is this possible?

**Comment by Andarist** [comment]
@glomotion your problem is very different from the issue described here. `@emotion/css` is eager so as soon as you call `css` stuff gets injected into the DOM - so it's not as flexible as `@emotion/react` with `<CacheProvider/>`.

You can use a **hack** like this: https://codesandbox.io/s/twilight-glade-0tr4l?file=/src/App.js . But remember that this is a hack and this won't work correctly with things like SSR.

**Comment by glomotion** [comment]
Oh that is perfect! 

In this case a Hack is fine, its really only needed to work around an issue with cypress component testing. 

Thank you @Andarist!

**Comment by tho-graf** [comment]
Hi @Andarist. we stumbled on a very similar issue. Our problem was that we had different modules. Our component lib had commonjs and our frontend esm.
