### ISSUE TITLE
css prop signature and css style signature is inconsistent when theme is used

### ISSUE THREAD

**Issue by terryyu** [emotion-js/emotion#1465]
**Current behavior:**
If you define styles which expect the theme property, it can not be shared for css prop and styled components.

```jsx
const colorStyles = ({ theme }) => css`
  color: ${theme.colors.primary};
`;

const Title = styled.h1`
  ${colorStyles};
  font-size: 30px;
`;
```

If you try to apply the color styles defined above to the css prop.
```jsx
<h2 css={colorStyles}>Start editing to see some magic happen!</h2>
```

An error will be thrown.
`Cannot read property 'colors' of undefined`

To fix that, you have to do
```jsx
<h2 css={theme => colorStyles({theme})}>Start editing to see some magic happen!</h2>
```

The reason is because the inconsistent signature.
```jsx
const colorStylesToBeUsedInStyledComponents = ({ theme }) => css`
  color: ${theme.colors.primary};
`;

const colorStylesToBeUsedInCssProp = theme => css`
  color: ${theme.colors.primary};
`;
```

In styled-components they are consistent.

**To reproduce:**

https://codesandbox.io/s/emotion-issue-p6qhf

**Expected behavior:**

Styles depending on the theme should be able to be shared regardless where they are used. The inconsistency is causing confusion.

**Environment information:**

- `react` version: 16.8.6
- `emotion` version: 10.0.15

**Comment by FezVrasta** [comment]
I think the issue is valid, may someone from the core team confirm it?

**Comment by Andarist** [comment]
I also believe that this is valid - need to think about it more, but I'll add this as a candidate for v11.

**Comment by mitchellhamilton** [comment]
I don’t think this is something we want to change. the reason that this is consistent in styled-components is that they pass props into the css prop whereas we don’t. Passing props into the css prop would require an extra object assign which we would rather avoid.

**Comment by terryyu** [comment]
Hi @mitchellhamilton thanks for taking a look! could you provide a simple code snippet about the extra object assign when passing props into the css prop?

You reminds me about another example, it would be nice if we can pass props into the css prop.
```jsx
function ColorCard({
  color,
}) {
  return (
    <button css={css`
      color: ${color};
    `}>{color}</button>
  )
}

function ColorButton({
  color,
}) {
  return (
    <button css={css`
      color: ${color};
    `}>{color}</button>
  )
}
```
It feels natural to extract the style and make it common.
```jsx
const colorStyles = ({ color }) => css`
  color: ${color};
`;

function ColorButton({
  color,
}) {
  return (
    <button css={colorStyles}>{color}</button>
  )
}

function ColorCard({
  color,
}) {
  return (
    <button css={colorStyles}>{color}</button>
  )
}
``` 
We can't do it with the current design.

**Comment by Andarist** [comment]
I believe that @mitchellhamilton just meant that `theme` for a css prop would have to be, somewhat artificially, wrapped in an object (if we would implement this). So internally instead of roughly doing this:
```js
const theme = useTheme(ThemeContext)
cssProp(theme)
```
we'd have to do this
```js
const theme = useTheme(ThemeContext)
cssProp({ theme })
```

> You reminds me about another example, it would be nice if we can pass props into the css prop.

The given example is just impossible to implement. `css` prop lacks the context of ColorCard props, it's completely unaware of them. It could potentially be aware of that `div`'s props but it's not something that we want to support because often you are using `css` prop on host elements (like `div`) but your "styling props" are not what you actually want to pass onto that div (it would show up in the DOM and React would warn you against that). We could filter them out like in case of the styled API but we refuse to do this because it forces us to maintain a props whitelist and this is something that `css` prop was designed to avoid.

Your example can be rewritten easily with just minor changes to:
```js
const colorStyles = ({ color }) => css`
  color: ${color};
`;

function ColorButton(props) {
  const { color } = props
  return (
    <button css={colorStyles(props)}>{color}</button>
  )
}

function ColorCard(props) {
  const { color } = props
  return (
    <div css={colorStyles(props)}>{color}</div>
  )
}
```

**Comment by terryyu** [comment]
@Andarist thanks for explaining!
I thought css prop and styled components are two interchangeable ways to work with predefined/imported styles. Now I realize they are designed with a little difference and constraints. Good to know!
