### ISSUE TITLE
Keyframes can affect the order in which styles are applied

### ISSUE THREAD

**Issue by zhzz** [emotion-js/emotion#1505]
Hello. Thanks for your great work guys!

We're using `emotion` package together with regular css-files, combining classNames via `cx` function. And I've just faced an issue with style-tags order.

**Current behavior:**
Emotion's style-tags are inserted before "regular-css" style-tags depending on keyframes presence.

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-18p8o

1. Observe the red color being correctly applied to the text
2. Uncomment the line 5 that imports test keyframes
3. Notice the color of the text that has changed to green due incorrect styles order

**Expected behavior:**

The text color remains red.

**Environment information:**

- `react` version: 16.8.6
- `emotion` version: 10.0.17

**Comment by Andarist** [comment]
There is no "incorrect" styles order here - it's just the order. Emotion can't predict what's your intention and it has to insert its style tag somewhere. You can though change the container for emotion styles by using `create-emotion` and configuring this however you want.

**Comment by zhzz** [comment]
Ok, but shouldn't that behavior be constant in this case?

**Comment by Andarist** [comment]
Emotion (bare emotion, not `@emotion/core`) creates styles eagerly - it has to do this, because it returns a string (a class name) to you so you can just use it directly as className prop value.

So whenever you call `css` in dev mode it just creates those styles and inserts it into the head AFTER its previous style tag (in prod mode it tries to insert everything into a single style tag through CSSOM APIs).

When you import & use those keyframes BEFORE your `.css` import you make that evaluated first - so emotion tag comes first (and later tags are always put just after the previous one) and then that `.css` import gets evaluated and it creates a new style tag which gets just inserted at the end of the head.

When you don't import those keyframes you effectively create first emotion styles INSIDE your render and thus emotion style creation gets delayed until that (and ofc that `.css` import already has done its job - so first emotion tag gets inserted after it).

**Comment by zhzz** [comment]
@Andarist thank you for such a great explanation! 

Yep, it works as I expect in prod. And that fact makes it even more confusing. The same code results differently in dev and prod. 

Now I'm just wondering, why not to always append styles to the end of the head in dev mode? I know that counting on the styles order is a bad way to go. But wouldn't it be more logical to keep their natural applying order?

**Comment by Andarist** [comment]
Actually the way it works now makes it work the same in dev & prod mode because emotion styles are always inserted "together" - either into a single style tag (up to 65000 rules) or into multiple but which are next to each other. So no foreign style should interleave them.

> The same code results differently in dev and prod.

The same code really shouldn't - in both cases the first emotion style tag gets inserted into DOM lazily while inserting the first rule. Could you showcase your problem with a demo?

**Comment by zhzz** [comment]
The demo will be pretty close to my repro. We have some overlapping styles in both css and js. And after the migration of keyframes on the Emotion, we found the styles were broken by the changed order of their insertion in dev mode.

If you don't think this is a bug we can close the issue. We've to rewrite our styles anyway.

**Comment by Andarist** [comment]
I believe there is no bug here, but would be good to confirm.
