### ISSUE TITLE
[TypeScript] Leverage declaration merging for themes

### ISSUE THREAD

**Issue by kripod** [emotion-js/emotion#1507]
**The problem**

Currently, a custom `styled` object should be created and exported from a file to be used in components.

- The given path may be far up inside the directory hierarchy, resulting in statements similar to `import styled from ‘../../../utils/styled’`
- External libraries (e.g. [Chakra UI](https://github.com/chakra-ui/chakra-ui)) can only use built-in type definitions of `@emotion/styled`, unless [hacky workarounds](https://github.com/kripod/gatsby-starter-strict/blob/e061ea4fdfb1801d8a5debd0912d05c2c0569dc9/tsconfig.json#L12-L16) are used for tricking compilers and editors

**Proposed solution**

Based on the [docs](https://www.styled-components.com/docs/api#typescript) of styled-components, [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) could be used for defining theme types. I am not aware of any drawbacks concerning this technique, especially if the old method of defining theme types remains available.

**Comment by Andarist** [comment]
There are examples of this behavior (declaration merging) being a source of troubles - https://github.com/emotion-js/emotion/issues/1257

I would expect the same problems can occur with what you propose here.

**Comment by Jessidhia** [comment]
The problem in #1257 is not related to `emotion` providing an interface that can be augmented by users -- it's related to `emotion` automatically augmenting React's interfaces even when it's not actually being used, just because its types were brought into scope (for example via a transitive dependency, say, `react-select`).

As far as I know there are no problems with users augmenting `styled-components`' `DefaultTheme` interface.

**Comment by Andarist** [comment]
> The problem in #1257 is not related to emotion providing an interface that can be augmented by users -- it's related to emotion automatically augmenting React's interfaces even when it's not actually being used, just because its types were brought into scope (for example via a transitive dependency, say, react-select).

Is `styled-components` doing this differently so it doesn't suffer from this problem? 

> As far as I know there are no problems with users augmenting styled-components' DefaultTheme interface.

Isn't it a problem with 2 component libraries built on top of a single css-in-js library (either emotion or styled-components) used in a single application when both would like to augment this DefaultTheme because they both come with ThemeProvider (wrapper around builtin css-on-js ThemeProvider)?

**Comment by Jessidhia** [comment]
Each `DefaultTheme` belongs to a different module. A full qualified name for them would be (for example) `import('@emotion/theming').DefaultTheme` and `import('styled-components').DefaultTheme`, which are different interfaces with the same name, and can be separately augmented.

The conflict here is that we have both emotion and `styled-components/cssprop` (note: **not** `styled-components`) trying to augment `import('react').Attributes`.

The way `styled-components` provides the `css` prop _with_ the `DefaultTheme` is with three options -- either the user adds `"styled-components/cssprop"` to their `compilerOptions.types` array in `tsconfig.json`, or they do an empty import (`import {} from 'styled-components/cssprop'`), which is interpreted as a type-only import with all types erased, or by using a triple-slash reference (`/// <reference types='styled-components/cssprop' />`).

The important part is that it's not done automatically, only via opt-in, which also opens up two more options: augmenting it yourself by using the `import('styled-components').CSSProp` type, which receives a theme  as its generic argument, or by not augmenting it at all, and thus not introducing a `css` property.

---

Furthermore, `@emotion/core` currently injects its `css` prop in two unrelated interfaces; `import('react').DOMAttributes` and (global) `JSX.IntrinsicAttributes`, when augmenting just `import('react').Attributes` should suffice for all element types.

**Comment by Andarist** [comment]
> Each DefaultTheme belongs to a different module. A fully qualified name for them would be (for example) import('@emotion/theming').DefaultTheme and import('styled-components').DefaultTheme, which are different interfaces with the same local name, and can be separately augmented.

I understand that styled-components and emotion have both different DefaultTheme - I'm rather concerned about 2 component libraries, both based on the same css-in-js library. Like if e.g. material ui were emotion-based and rebass would also be emotion-based, both would support theming and both would be augmenting the DefaulTheme. Or is this use case unrealistic? How both of those libraries should provide their themes? The problem kinda is not even that tied to TS, because they would potentially also clash in runtime, but still.

> The important part is that it's not done automatically, only via opt-in

CSS prop is kinda a preferred way now of using emotion, so it would be great if we could support this correctly without the need to introduce extra config for a user - but if that's the only option to support this correctly, then I guess we should require it from our users.

What would be your recommendation? What do you believe we should do?

**Comment by Andarist** [comment]
This has been implemented in https://github.com/emotion-js/emotion/pull/1609 and will be released in the upcoming v11.
