### ISSUE TITLE
styled components typed as "any"

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1515]
**Current behavior:**

Right now the styled components are annotated with `any`, I was wondering why this decision was made and if it's something you'd be interested in fixing? I'm referring to the Flow types.

**Expected behavior:**

I would expect the generated styled components to have a `React$ComponentType` type rather than `any`.

**Environment information:**

- `react` version: 16.9.0
- `emotion` version: 10.0.7

**Comment by Andarist** [comment]
Isn't the return type being annotated here - https://github.com/emotion-js/emotion/blob/a8b9a7f049f9773a57d76c7b380d8e48110f1569/packages/styled-base/src/index.js#L58 ?

**Comment by FezVrasta** [comment]
I think the styled component is https://github.com/emotion-js/emotion/blob/a8b9a7f049f9773a57d76c7b380d8e48110f1569/packages/styled-base/src/index.js#L85

At least, Flow marks `const Foo = styled.div()` as `any`

**Comment by Andarist** [comment]
That's weird because simplified version if this seems to work "as expected":
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKADwEoAuMbTAWwCMBTAJzAG9UAkLhIBnfGACGjCdgCeYALxgA5MsFcO+TF1ITUAX3TDsYsGwk8l5KrVRA

Could you check which version of the flow are you using? Might be that this is already fixed or that this is an issue with flow itself, not emotion's code.

**Comment by FezVrasta** [comment]
I'm on 0.108.0, you can try it yourself with the below code:

```js
const Foo: string = styled.div();
```

this should throw a type error, but it doesn't

**Comment by FezVrasta** [comment]
I know it doesn't proves much, but here's a screenshot of Flow being happy with it.

![image](https://user-images.githubusercontent.com/5382443/65428818-5bf56880-de15-11e9-85fb-68011638f4ba.png)

**Comment by Andarist** [comment]
Could you prepare a runnable repro case?

**Comment by FezVrasta** [comment]
Yeah I wanted to make one on CodeSandbox but it ends up they don’t support Flow 😒 I’ll try to prepare one today

**Comment by FezVrasta** [comment]
I didn't have time to prepare a repro yet, but I just noticed that `@emotion/styled/macro` doesn't provide a `.flow` counterpart, so that files is marked as untyped by Flow (leading to `any` annotation).

**Comment by FezVrasta** [comment]
I managed to make Flow kinda work on CodeSandbox 🥳

https://codesandbox.io/s/gatsby-starter-default-3u6vt

In the terminal, run `yarn flow` to see the output:

![image](https://user-images.githubusercontent.com/5382443/67386336-0daec300-f595-11e9-9cea-09b73a5b8636.png)

**Comment by FezVrasta** [comment]
@Andarist #1562 doesn't fix this issue, it's a separated problem.

**Comment by Andarist** [comment]
#1562 fixed the issue of macros being any though, right?

**Comment by FezVrasta** [comment]
#1562 fixed the issue of macros being any _because imported from an untyped file_ (so that means you will not get the `no-untyped-import` Flow linting error anymore)

But they will still be `any` because of the bug you can reproduce with my CodeSandbox.

**Comment by Andarist** [comment]
This is super weird - but also seems buggy on the Flow's side, because I can't force the returned object here:
https://github.com/emotion-js/emotion/blob/95a43a290339d245b6c036874bd0d010c2b6839d/packages/styled-base/src/index.js#L223
to be of the proper type (and it's any, so I should be able to assign whatever type i want to it, right?). I was also unable to reproduce this problem on the playground, even though I've tried fair share of combinations.

I think I give up for now.

**Comment by Andarist** [comment]
I've bisected our code to see what triggers this and it seems that the existential type here is the culprit:
https://github.com/emotion-js/emotion/blob/9ff27de56d4af7a05f47067a650beea49d17611e/packages/styled-base/src/utils.js#L26

When I try to fix it I bump into other typing errors though - they are probably fixable, but because I'm not a flow user it really is hard to do that for me. Could you try to improve those typings there? It seems that you care about this and have more experience with flow than me.

**Comment by FezVrasta** [comment]
the existential type is deprecated, I wonder if they just replaced it with `any`.

I'll look into it.

**Comment by FezVrasta** [comment]
I pushed some work here https://github.com/emotion-js/emotion/pull/1570
