### ISSUE TITLE
More options/values for labelFormat

### ISSUE THREAD

**Issue by kud** [emotion-js/emotion#1559]
**The problem**

For the moment I use `"labelFormat": "[dirname]-[filename]--[local]",` but that's not enough for me.

**Proposed solution**

I would like that `dirname` takes all the folders.

**Context**

I'm here:  `/src/pages/Home/Main/Content.js` with: 

```javascript
const Heading = styled.div``

class HomePageMainContent extends React.Component {}
```

I would like that the className generated for `Heading` is:

- either `xxx-HomePageMainContent--Heading` (`random-NameOfTheReactClass--NameOfTheLocal`)
- or `xxx-pages-Home-Main-Content--Heading` (`random-The-Whole-Path--NameOfTheLocal`) 

Thank you :)

**Comment by Andarist** [comment]
I agree that `dirname` for this is a little bit confusing, because usually `dirname` refers to the full path. Would you by any change have a better name for what is currently a `dirname` pattern? Maybe something like `parentDir`?

Anyway - I feel like we just can't satisfy all possible use cases and maybe we should just allow `labelFormat` to be a function? That way you could return whatever you want (based on filename).

**Comment by mitchellhamilton** [comment]
> Anyway - I feel like we just can't satisfy all possible use cases and maybe we should just allow labelFormat to be a function? That way you could return whatever you want (based on filename).

I would be in favor of allowing this

**Comment by Andarist** [comment]
This was implemented in https://github.com/emotion-js/emotion/pull/1651 and will be included in upcoming v11 release
