### ISSUE TITLE
Babel plugin changes don't invalidate jest cache

### ISSUE THREAD

**Issue by liamcmitchell-sc** [emotion-js/emotion#1593]
**Current behavior:**

Changes to babel plugins (babel-plugin-emotion, babel-plugin-jsx-pragmatic, babel-preset-css-prop) that change classname hashes, do not invalidate jest cache (and cause devs to spend hours tracking down cause of diffs).

**To reproduce:**

Reproduction is a bit of a pain. You need a snapshot from an older version of emotion (pre [10.0.23](https://github.com/emotion-js/emotion/commit/1bb3efe399ddf0f3332187f3c751fbba9326d02c#diff-c836b429f415a9dd4f5784271ad39a5c) maybe), upgrade to latest, re-run snapshot tests - should pass, run `jest --no-cache` - should fail.

**Expected behavior:**

Caches to be invalidated automatically on upgrade of babel plugins.

**The fix**

Jest's caching behavior is described here: https://github.com/facebook/jest/issues/7584#issuecomment-451939931
As mentioned in Babel's docs, serializing options is not 100% foolproof but the only option available right now.

I have fixed this in my project by adding the emotion core version number to the babel preset options. This should automatically invalidate the cache when we bump emotion versions.
```js
// babel.config.js
  presets: [
    [
      '@emotion/babel-preset-css-prop',
      {
        // Make sure emotion version is included in jest cache hash.
        // https://github.com/facebook/jest/issues/7584#issuecomment-451939931
        cacheBuster: require('@emotion/core/package.json').version,
      },
    ],
  ],
```

Even if it shouldn't be the responsibility of emotion to manage jest cache invalidation, it would probably save developers hours of future headache if some kind of version was included in the preset config by default.

**Comment by liamcmitchell-sc** [comment]
Actually, not sure yet if this really fixes my issue. I still think the issue is with cached babel transforms. Investigating further.

**Comment by Andarist** [comment]
I'm not entirely sure if it's possible for us to add such cacheBuster option internally - because Babel might try to serialize plugins when calculating the cache key BEFORE resolving the plugins. 

This is certainly worth looking into - but it might be the case that we won't be able to "fix" this on our part. This would be a good feature request for Babel though.

**Comment by liamcmitchell-sc** [comment]
Jest cache is calculated by serializing the fully resolved Babel config - the output from https://babeljs.io/docs/en/babel-core#loadoptions

I'm leaning towards adding my whole package.json to babel config so that the cache is busted on any dep change.

The fix I have above adds the version to the preset config, which is then spread onto the jsx plugin config when resolved.

A similar "fix" could be done in babel-preset-css-prop:
https://github.com/emotion-js/emotion/blob/master/packages/babel-preset-css-prop/src/index.js#L27-L36
```js
      [
        emotion,
        {
          sourceMap,
          autoLabel,
          labelFormat,
          instances,
          cssPropOptimization: true,
          cacheBuster: emotion.version, // not sure the best way to get version value 
        }
      ]
```

**Comment by liamcmitchell-sc** [comment]
Please close if you think it's best solved upstream. Just wanted to make sure this issue is documented somewhere in case others run into it.

**Comment by Andarist** [comment]
I think it's worth fixing it here - if possible. I guess you've wasted on this some time so it would be good to prevent others from wasting it as well. 

I'll try to repro this when I get some free time to see how it behaves when I add cacheBuster-like option.

**Comment by anilanar** [comment]
Just wanted to chime in here that my team has also wasted some time on this when we had hotfix/development branches had different babel versions and different devs would update snapshots with different hashes due to the confusion.

**Comment by Andarist** [comment]
> A similar "fix" could be done in babel-preset-css-prop:
https://github.com/emotion-js/emotion/blob/master/packages/babel-preset-css-prop/src/index.js#L27-L36

I'm afraid it can't because [this](https://github.com/facebook/jest/blob/938f1466be978a9f2646e6710646eb6439134ea6/packages/babel-jest/src/index.js#L62) doesn't hold resolved presets, so adding any option internally to one of the plugins in a preset doesn't affect the stringified value 😕

I've thought about this few times and looked through Jest & Babel code/options and I don't think there is anything we can do about this (unfortunately). The best thing I've come up with is this: https://github.com/preconstruct/preconstruct/issues/286 and it still wouldn't really cover for all cases. 

I'm going to close this issue as it's, sadly, not actionable here.
