### ISSUE TITLE
Adding nonbreaking white space to a pseudo elements content breaks the style

### ISSUE THREAD

**Issue by ChrisW-B** [emotion-js/emotion#1601]
**Current behavior:**

When I use a nonbreaking white space character (\00a0) in a pseudo element's content property, the css does not appear after building
**To reproduce:**
Sample code using the nbsp:
```javascript
export const DetailListItem = styled.li`
  border-top: 0.1rem dashed rgba(148, 174, 229, 0.25);
  display: grid;
  grid-gap: 1rem 0;
  grid-template: auto / 15rem auto;
  padding-top: 1rem;

  code {
    background-color: rgba(27, 31, 35, 0.05);
    border: 1px solid #e1e1e8;
    border-radius: 3px;
    color: #d72b3f;
    font-family: 'Operator Mono', Consolas, monaco, 'Ubuntu Mono', courier, monospace;
    font-size: 85%;
    margin: 0;
    padding-bottom: 0.2em;
    padding-top: 0.2em;

    &::before,
    &::after {
      content: '\00a0 ';
      letter-spacing: -0.2rem;
    }
  }
`;
```

1. ...
2. ...
3. ...

**Expected behavior:**

**Environment information:**

- `react` version: 16.11.0
- `emotion` version:
  - `@emotion/core`: 10.0.22
  - `@emotion/styled`: 10.0.23
  - `@emotion`: 10.0.22
  - `babel-plugin-emotion`: 10.0.23

**Comment by Andarist** [comment]
We warn against this in development:
https://github.com/emotion-js/emotion/blob/c53646d5ddf453a480da1cd4428773bddc93c30f/packages/serialize/src/index.js#L364-L366

However, the warning can be given only when using untranspiled JavaScript or spec-compliant transforms. I suppose you have an outdated Babel version and thus you don't see the warning about it and this fails silently.

Basically because you write CSS in JS you have to escape twice - once for JS parser and once for CSS one. So you should make such change to make this work:
```diff
    &::before,
    &::after {
-      content: '\00a0 ';
+      content: '\\00a0 ';
      letter-spacing: -0.2rem;
    }
  }
```

Some more information can be found here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences

**Comment by selrond** [comment]
Just had to deal with this but in `styled-components`; a good way to handle the double-escaping problem is to just declare what you want to escape as a constant, so your IDE will pick up any unescaped stuff:

```js
const NBSP = '\\00a0'

const Component = styled.div`
  :before {
    content: '${NBSP}';
  }
`
```
