### ISSUE TITLE
[SUPPORT] Why strings are not allowed as CSS prop values?

### ISSUE THREAD

**Issue by lcswillems** [emotion-js/emotion#1695]
I have this code:

```
<div css={`color: red;`}>Hi!</div>
```
but I get this error:
```
Error: Strings are not allowed as css prop values, please wrap it in a css template literal from '@emotion/css'
```

Why? I don't need to do it with Styled-Components.

The library should detect if I input a string and if it is the case, it should wrap it in this `css` wrapper.

**Comment by Andarist** [comment]
Wrapping your string styles with `css` like in example below gives you additional benefits - such as prettier formatting and in-editor syntax highlighting. That's why we prefer to encourage its usage.
```js
<div css={css`color: red;`}>Hi!</div>
```

**Comment by lcswillems** [comment]
VSCode and Prettier already highlights correctly without using `css`. So I don't see any reason. Moreover, you could allow people to use `css` if they want, instead of forcing them (for any reason).

Using `css` adds useless `emotion` imports, makes code more painful to write, and makes people painful to migrate to Emotion.

**Comment by Andarist** [comment]
Interesting - I was sure that prettier doesn't handle this. We'll consider changing this in the upcoming v11.

**Comment by lcswillems** [comment]
That's great!

**Comment by Andarist** [comment]
We've decided not to change that - while it's true that plain strings are handled nicely by Prettier etc when used directly as css prop value, but it doesn't work for:
```
<div
  css={[someStyles, `color:
   hotpink;
          `]}/>
```
It's not only that though - any other place with plain string can't benefit from autoformatting, syntax highlighting etc when **not** wrapped in `css` as those tools just cannot know that "random" strings are in fact css declarations.

You also can't easily just interpolate stuff into a plain string because the interpolation will get stringified immediately, producing often invalid CSS. We go with a philosophy outlined [here](https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-arrowparens-to-always-7430httpsgithubcomprettierprettierpull7430-by-kachkaevhttpsgithubcomkachkaev) - once you need to interpolate something into a string you need to wrap the whole thing with `css` anyway, so why bother not adding it in the first place? Optimize for a possible refactor/code changes.

I hope you understand our arguments.

**Comment by lcswillems** [comment]
There is something I don't understand. This:

```
<div
  css={[someStyles, `color:
   hotpink;
          `]}/>
```

won't be well formated, but this:

```
<div
  css={css([someStyles, `color:
   hotpink;
          `])}/>
```

will be? I don't understand why there is a difference. Both code are isomorphic. If I can well format the first one, I could well format the second and reciprocally.

I also read the blog post of Prettier and read this part about arrow function. I understand why they do it. In their case, the refactoring between single argument function and multiple arguments function is frequent. But in there case here, I don't think so (I might be wrong). I have no occurrence of CSS concatenation in my whole codebase VS tons of inline CSS declarations.

**Comment by Andarist** [comment]
The given example won't be formatted by Prettier, it's not about wrapping an array with `css`, but rather the string itself:
```js
<div
  css={[someStyles, css`color:
   hotpink;
          `]}/>
```
Check out in the Prettier playground [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBuAPAEwJYDcA6UABEWAM5kC8w5ZAFANpkQC2cAyjAJ4A2cZAGiIADSDwgAnJIRJEAFhBgAHbFADWqGbO0lhAXQCUAXwD0APkKWoGHAWKkK1Jqw7c+gh2VERxUrfMUVdU17HVl9UzMQARAIJRhsaDJkUABDCQkIAHcABXSEZJRUnizUrmSYgCMJVLA1OBh2JVrVAHNkGAkAVzgYuRgWHgB1OWx4MmawDgKxvDGuZHAKaJBVMjgJGBya1pZU5AAzYvWYgCsyAA8AIRq6hvZUtgAZVThD496Qc4v2Nr4ARS6ijeSCOPBOIGaEnWEkWlVSlTgPBWSgkqhgQ2wmBgcmQAA4AAwxVEQdZDGpKRao-gbXBvGIARyB8G2cUKIFSZAAtFA4HBMPyVhI4EzsMLtqldvtQR8YusWNgOt1PmQ-nBAcD3uDPjAEZjsbikAAmGKdVLYHhtADCrD2i34AFYVl11gAVBGFMEQ3A9ACSUAFsHYYDR8QAggHOLwQV64EYjEA).

When it comes to the refactoring argument I mean mainly this:
```diff
<div
-  css={`
+  css={css`
    color: hotpink;
+   ${otherStyles}
  `}
/>;
```
vs
```diff
<div
  css={css`
    color: hotpink;
+   ${otherStyles}
  `}
/>;
```

Without `css` there are also problems around patterns like this:
```js
var foo = `
  color: hotpink;
`
<div
  css={foo}
/>;
```
In this situation it's hard for any tool to do anything special about this string - this includes formatting, syntax highlighting, source map generation, auto label generation etc.

**Comment by lcswillems** [comment]
Thank you for your explanations!

I see the problem in the first case.

In the second case, I would say that if the person wants to enforce syntax highlighting it can add a `css` before the string. However, we will get the refactoring issue (more likely than the other refactoring issue but not that much from my point of view).

What I would suggest is to make `css` optional in `<div css={...} />`.

**Comment by Andarist** [comment]
Problem is that in the end this always gets resolved at runtime - we can't just allow plain strings if they are passed "inline" to the css prop because it's no different from the runtime perspective to a string passed from somewhere else. 

We could allow this within a Babel plugin (we could add `css` automatically) but then you end up with TS typing problems, because you have to allow strings at all times within types. It also makes up for a user confusion - why strings are allowed in certain situations and why they are not in others?

I understand your argument about this being sometimes boilerplate-y, but we need to consider all pros and cons of this. It's also currently a single report about this being problematic - so we don't want to change this because of that, at least - not just yet.

Keep also in mind that support for this can be added in userland through a custom Babel plugin or something like `patch-package`.

**Comment by lcswillems** [comment]
I understand your decision!

Good luck for the development of the library.

**Comment by lazeebee** [comment]
> Problem is that in the end this always gets resolved at runtime - we can't just allow plain strings if they are passed "inline" to the css prop because it's no different from the runtime perspective to a string passed from somewhere else.

> We could allow this within a Babel plugin (we could add css automatically) but then you end up with TS typing problems, because you have to allow strings at all times within types. It also makes up for a user confusion - why strings are allowed in certain situations and why they are not in others?

@Andarist Can I bring up this issue again? What's the problem of allowing strings at all times the same way object are allowed?

**Comment by Andarist** [comment]
@lazeebee there are planty of arguments in this thread already
