### ISSUE TITLE
CRA Typescript: CreateStyled and styled in @emotion/styled/marco doesn't work

### ISSUE THREAD

**Issue by albusphan** [emotion-js/emotion#1754]
**Current behavior:**
Using ```CreateStyled``` and ```styled``` from ```@emotion/styled``` in my CRA Typescript project keep throw error:
```Error: Component selectors can only be used in conjunction with babel-plugin-emotion.```

Code :
```
import styled, { CreateStyled } from '@emotion/styled'

import { Theme } from './index'

export default styled as CreateStyled<Theme>
```

**Environment information:**

- `react` version: 16.12.0
- `emotion` version: 10.0.27

Note: The ```styled``` will work if using standalone in a component

**Comment by Andarist** [comment]
This, unfortunately, doesn't work with pure TS in emotion 10. There are no plans to fix it because we have chosen other way of customizing the Theme type in the upcoming v11 (already available on np mand very much usable!):
https://github.com/emotion-js/emotion/issues/1606#issuecomment-582223628

I would recommend migrating to v11 if you are interested in this.

**Comment by reynnan** [comment]
Are there any workaround?

**Comment by Andarist** [comment]
Closing because of what has been stated in the above comment.
