### ISSUE TITLE
Unexpected "You have illegal escape sequence..." in Chrome DevTools

### ISSUE THREAD

**Issue by ThisIsManta** [emotion-js/emotion#1755]
**Current behavior:**

I have got the error message saying
> You have illegal escape sequence in your template literal, most likely inside content's property value.
Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".
You can read more about this here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences

While my one and only `tsx` file never contains a backslash.
```tsx
import React from 'react'
import ReactDOM from 'react-dom'
import { css } from '@emotion/core'

const RED = 'red'

ReactDOM.render(
  <div
    css={css`
      color: ${RED};
    `}
  >
    Hey
  </div>,
  document.getElementById('root')
)
```

**To reproduce:**

1. `git clone https://github.com/ThisIsManta/parcel-ts-emotion`
2. `yarn`
3. `yarn start`
4. Open http://localhost:1234/ in Google Chrome (may possible to reproduce in other browsers as well)

**Expected behavior:**

Expect NOT to see the error message in Google console.

The error message **will be gone** if I put `"resolutions": { "@emotion/serialize": "0.11.4" }` in my [_package.json_](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) as the latest version of `@emotion/core` auto installs **v0.11.5** which prints the error message unexpectedly.

![image](https://user-images.githubusercontent.com/5592654/74089037-72077b00-4acf-11ea-89f3-8757e05e7276.png)

**Environment information:**

- I'm using Parcel + TS + Emotion via [_.babelrc_](https://github.com/ThisIsManta/parcel-ts-emotion/blob/master/.babelrc)
- `react` version: 16.12.0
- `@emotion/core` version: **v10.0.27**
- See the rest in [_package.json_](https://github.com/ThisIsManta/parcel-ts-emotion/blob/master/package.json)
- Chrome for Windows: 80.0.3987.87 (Official Build) (64-bit)

**Comment by Andarist** [comment]
Thank you for the repro case! It seems that we insert source map string in a confusing way for tagged template iteration. I'm a little bit surprised that this is the first report about this as the scenario is quite basic - so maybe there is something special about your setup.

Either way - I will fix it, but it might take me some time because I'm super busy right now.

**Comment by ThisIsManta** [comment]
@Andarist, thanks for your reply. Yeah, there might have something to do with my setup as I’m not a Babel expert. Ultimately, I want to use Parcel+TypeScript+Emotion. If you know how to config this properly, please enlighten me.

In this meantime, I can just downgrade `@emotion/serialize` to 0.11.4 which works perfectly fine.

**Comment by mansourkheffache** [comment]
+1

Having the exact same issue.

**Comment by Andarist** [comment]
As mentioned - I'm super busy right now. `+1` comment is not really helpful in any way - if you care about the issue at hand I encourage you to just fix it and prepare a PR with the fix. If you don't want to do that, please just wait patiently for the fix.

**Comment by tomitrescak** [comment]
Hi, this started to reappear.

I have this: 
import { css } from 'emotion'; 
export const breakingLabel = css`
  display: block;
  font-weight: bold;
  margin-top: 3px;
  margin-bottom: 3px;
`;

This is what is a second parameter of what is coming to args:

```
;label:breakingLabel;/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJ... */
```

This is error:

You have illegal escape sequence in your template literal, most likely inside content's property value.
Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".

Raised here:

```
// serialize.browser.esm.js:274

if (process.env.NODE_ENV !== 'production' && strings[i] === undefined) {
    console.error(ILLEGAL_ESCAPE_SEQUENCE_ERROR);
}
```
Truth is, that the args has length 2 but strings only length 1

**Comment by Andarist** [comment]
Please make sure you are using the latest version of our babel plugin and if you do - please prepare a runnable repro case. I can't provide any further help without actually being able to debug this.

**Comment by tomitrescak** [comment]
Ok, updating plugin solved the issue. Thanks for your feedback.

**Comment by tills13** [comment]
Apologies in advance for digging up an old issue. 

I'm seeing this on a Next 12.2 project using their Emotion SWC compiler -- just hoping to get some clarification before filing an issue with them. Can you briefly explain the logic behind [these lines](https://github.com/emotion-js/emotion/blob/ce9873faabef8baf4eeebf8fab0d7b1a46ff74c7/packages/styled/src/base.js#L94-L97)? Particularly in the context of sourceMap insertion?

Let's say I have 

```
const Element = styled.span`
  display: block;
`
```

Note how there's no interpolation. This means the anon function in the linked lines should receive `[['display: block']]` as its arguments. With sourcemaps enabled, the function receives the sourcemap as the second arg (implying interpolation, not sure if that's relevant).

`args.length === 2`
`args[0][1] === undefined` 

Despite there being no escaping at all, I receive the error talked about in this issue. 

In all honesty, I really don't see how that particular block of code checks for illegal escape sequences at all since escaped sequences (valid or not) don't result in extra args.
