### ISSUE TITLE
babel-preset-css-prop fails to put label when theme is typed

### ISSUE THREAD

**Issue by escorponox** [emotion-js/emotion#1785]
**Current behavior:**

Classname has no label when we type the theme as explained in documentation.

**To reproduce:**

1. Clone this repo: https://github.com/escorponox/emotion-babel-preset-report
2. yarn
3. Check the results

**Expected behavior:**
The styled component should have the label in the classname as configured in the babel-preset-css-prop

**Environment information:**

    "emotion-theming": "^10.0.27",
    "@emotion/core": "^10.0.21",
    "@emotion/styled": "^10.0.17",
    "react": "16.12.0",
    "react-dom": "16.12.0"

**Comment by escorponox** [comment]
![image](https://user-images.githubusercontent.com/5127194/75888246-5b80e500-5e2b-11ea-8cf9-38dcee3a37cb.png)

**Comment by Andarist** [comment]
This got fixed in https://github.com/emotion-js/emotion/pull/1220 and is already released as part of our upcoming v11. I'm afraid that we can't afford the time to backport this into v10, but I strongly encourage you to try out v11. Especially given the fact that its TS types got reworked from scratch and allow for typing Theme globally which should result in way fewer reasons to create your own wrappers around `styled`.
