### ISSUE TITLE
Pairing up different classNames (with nesting) as for the same rule

### ISSUE THREAD

**Issue by nikoloza** [emotion-js/emotion#1814]
**The problem**

how would we group up selectors under the same rule like:

```css
.selected,
ul > li:hover {
  /* */
}
```

Right now it would duplicate (and not reuse) if we'd write it like this:
```js
const selected = css`border-bottom: 1px solid gray`
const ul = css`
  li:hover { ${selected} }
`
```

**Proposed solution**

1. We would just use reference which would just group (and not duplicate) those selectors in the scenario above. 

2. Or we could use a helper function to group up a few selectors

```js
group(selected, ul['li:hover'])
```

**Comment by Andarist** [comment]
I'm afraid I don't quite understand the issue here. Could you describe it in more detail? Which part do you consider a problem? Boilerplate of connecting things together? Producing multiple rules rather than a single rule for shared styles?

**Comment by nikoloza** [comment]
@Andarist 

> Producing multiple rules rather than a single rule for shared styles?

Yes, to reuse styles for multiple rules

**Comment by Andarist** [comment]
This is explicitly a non-goal for Emotion. We create actual rules as lazily as possible and this is not causing any problems because it's no different to have 2 rules with the same declarations and to have an equivalent single rule with multiple selectors.

Implementing this would increase the complexity a lot for a little to no gain.

**Comment by Andarist** [comment]
As mentioned - this doesn't align with our goals, so I'm going to close this issue as non-actionable for us.
