### ISSUE TITLE
If I import `keyframes` from `emotion` it works. If is from `@emotion/core` it doesn't. I create the keyframe dynamically inside the react component with an effect and then set it in the state.

### ISSUE THREAD

**Issue by stevemarksd** [emotion-js/emotion#1839]
If I import `keyframes` from `emotion` it works. If is from `@emotion/core` it doesn't. I create the keyframe dynamically inside the react component with an effect and then set it in the state.

```
keyframeState
useEffect(
I set the keyframeState here
)
render the component like this:

<div style={{
    animation: `${dragTransition} 2s ease infinite`
  }}/>
```

**Current behavior:**

a class is added to the classNames, but that class is not injected in the head styles, so nothign happens.

**To reproduce:**

If I import `keyframes` from `emotion` it works. If is from `@emotion/core` it doesn't. I create the keyframe dynamically inside the react component with an effect and then set it in the state.

```
keyframeState
useEffect(
I set the keyframeState here
)
render the component like this:

<div style={{
    animation: `${dragTransition} 2s ease infinite`
  }}/>
```

**Expected behavior:**

work

**Environment information:**

    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",
    "react": "^16.13.1",

**Comment by Andarist** [comment]
Imported functions from `@emotion/core` do not create simple strings that you can use - they return opaque objects (which you should not read/tamper with in your code) which are supposed to be used by our internal logic when those values get passed to emotion. `style` prop bypasses our logic as it's just a regular, non-aware of emotion, prop.

To make this work you should use css prop, rather than style.

**Comment by Andarist** [comment]
Closing as I've already answered this in the past and haven't heard back from the OP since then.
