### ISSUE TITLE
Targeting another emotion component does not work.

### ISSUE THREAD

**Issue by josh08h** [emotion-js/emotion#1899]
**Current behavior:**

I am following the docs [here](https://emotion.sh/docs/styled#targeting-another-emotion-component) in order to target another emotion component. Copying the example does not work as no child component styles are applied.

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-ll8py?file=/src/index.js

**Expected behavior:**

The child component should be green but it's red.

**Environment information:**

- `react` version: react@16.13.1
- `emotion` version: emotion@9.2.6

**Comment by Andarist** [comment]
@Slapbox could you prepare a runnable repro case of your problem?

**Comment by Slapbox** [comment]
@Andarist sure I'd be happy to, but this functionality relies on the Babel plugin being used, right? If so, does that mean I can't create a repro in CodeSandbox, or is there some way to enable the plugin in that environment?

**Comment by Andarist** [comment]
For the most part, you should be able to use Babel Macros. Just change the import path from `@emotion/styled` to `@emotion/styled/macro`.

**Comment by Slapbox** [comment]
Oh that's nifty!

[This should do it](https://codesandbox.io/s/emotion-issue-template-forked-yomkh?file=/src/index.js), but CodeSandbox is being a bit glitchy for me and sometimes when I load it I'm just getting a blank white screen instead of the error message.

![image](https://user-images.githubusercontent.com/6835891/91098293-38dbc600-e62f-11ea-80bf-4a4bb98518bf.png)

**Comment by Andarist** [comment]
Ok, I've dropped using Babel Macros there as I hadn't much time to figure out what's wrong. I've prepared an equivalent demo though: https://codesandbox.io/s/emotion-issue-template-forked-odeq5?file=/src/index.js . What Babel plugin does is that it just inserts an option argument with a `target` property and this can be used manually with success. Can't reproduce your problem with the project exploding - everything works fine, so you would have to prepare a repository with your issue reproduced so I could take a deeper look at your problem.

**Comment by Slapbox** [comment]
Thanks so much for taking the time to explain that! 

I'd like to create a full repro, but being honest it's unlikely that I'll be able to find the time before Emotion 11 is finalized since it's only affecting a single line of our entire codebase.

The use of `target` seems really promising, but can that be used in conjunction with the Babel plugin? I'm guessing not since you dropped the use of the Babel Macros to demonstrate it.

I see that the chosen name in `target` gets applied as a CSS class on CodeSandbox, but in our environment it doesn't seem to have any effect on the className(s) assigned to the component, and I'm assuming that's due to our use of the Babel plugin.

Thanks again @Andarist for being one of the greatest people on GitHub!

**Comment by Andarist** [comment]
> The use of target seems really promising, but can that be used in conjunction with the Babel plugin? I'm guessing not since you dropped the use of the Babel Macros to demonstrate it.

The Babel plugin would probably override the manual target - it literally inserts this target to the code, this is how component selectors are implemented. I've just dropped using the Macros because didn't have time to figure out why they didn't work on the codesandbox (and they should). So I've prepared an equivalent demo without a Babel plugin being used - but it contains very similar code to which Babel plugin transpiles styled components.
