### ISSUE TITLE
Parentheses within a url() cause issues for global styles

### ISSUE THREAD

**Issue by stezu** [emotion-js/emotion#1935]
**Current behavior:**

When a global style definition contains parentheses within a `url()`, subsequent style definitions are unintentionally scoped to the earlier style definition. This behavior also cascades which causes interesting results.

**To reproduce:**

I [created a CodeSandbox](https://codesandbox.io/s/emotion-rgb-bug-74bf3?file=/src/App.js) showing the failure with some inline descriptions of the observed behavior. More specifically, you can see that with this global style definition:
```jsx
<Global
  styles={css`
    .rgb {
      /* some styles containing a url() with embedded parentheses */
    }
    .named {
      /* some styles containing a url() without embedded parentheses */
    }
  `}
/>
```

The output `style` elements looks like this:
```html
<style data-emotion="css-global">
  .rgb{ /* the expected styles */ }
</style>
<style data-emotion="css-global">
  .rgb .named{ /* the expected styles */ }
</style>
```

**Expected behavior:**

The output `style` elements should look like this:
```html
<style data-emotion="css-global">
  .rgb{ /* the expected styles */ }
</style>
<style data-emotion="css-global">
  .named{ /* the expected styles */ }
</style>
```

**Environment information:**

- `react` version: 16.12.0
- `@emotion/core` version: 10.0.28

**Comment by Andarist** [comment]
The underlying cause might be similar to the one causing [this problem](https://github.com/emotion-js/emotion/issues/1313). It has been fixed in the upcoming v11 and I've checked that your problem has been fixed as well: https://codesandbox.io/s/emotion-rgb-bug-5y1v2?file=/src/App.js . Unfortunately, there is 0 chance of backporting the fix to v10 - I encourage you to migrate to v11 which should be released this summer and there are no more substantial breaking changes planned for it.
