### ISSUE TITLE
No style typings when using `styled(Animated.View)` in React Native and Emotion 11

### ISSUE THREAD

**Issue by efoken** [emotion-js/emotion#1959]
**Current behavior:**

When I use `styled(Animated.View)({ ... })` my style object seem to have the `any` type, instead of `ViewStyle`.

**To reproduce:**

1. Create a styled animated component like described above.
2. See that the styles have no type (no autocompletion in VSCode) 😃 

**Expected behavior:**

Style object should be of type `ViewStyle`.

**Environment information:**

- `react` version: 16.11.0
- `emotion` version: ^11.0.0-next.14

**Comment by Andarist** [comment]
Could you prepare a runnable repro case for this? It would help me get to your issue way faster.

**Comment by efoken** [comment]
Working example:

```tsx
const StyledView = styled(View)(({ theme }) => ({
  backgroundColor: '#fff', // <-- Type Error
  height: 20,
  width: 20,
});
```

With TypeScript error:

```tsx
const StyledView = styled(View)(({ theme }) => ({
  backgroundColor: 1, // <-- TypeScript error
  height: 20,
  width: 20,
});
```

Using `Animated.View` there is no error and the object seems to have `any` type:

```tsx
import { Animated } from 'react-native';

const StyledView = styled(Animated.View)(({ theme }) => ({
  backgroundColor: 1, // <-- no error here
  height: 20,
  width: 20,
});
```

**Comment by Andarist** [comment]
This is not a **runnable** repro case. Setting up a repro etc takes time, context switching and is prone to doing things differently from the reporter - that's why having a runnable repro case that can just be cloned so I could get to hacking right away would be much appreciated.

**Comment by Andarist** [comment]
This partially happens because the `style` prop for Animated components is equivalent to something like:
```ts
false | RN.ViewStyle | RN.RegisteredStyle<RN.ViewStyle> | RN.RecursiveArray<false | RN.ViewStyle | RN.RegisteredStyle<RN.ViewStyle> | null | undefined> | Animated.WithAnimatedValue<StyleProp<RN.ViewStyle>> | null | undefined
```

We process this and extract things that match this:
```ts
type ReactNativeStyle = RN.ViewStyle | RN.TextStyle | RN.ImageStyle
```

but surprisingly this brings us in this case to:
```ts
type Test1 = RN.ViewStyle | Animated.WithAnimatedValue<StyleProp<RN.ViewStyle>> extends RN.ViewStyle | RN.TextStyle | RN.ImageStyle ? true : false
type Test2 = Animated.WithAnimatedValue<StyleProp<RN.ViewStyle>> extends RN.ViewStyle | RN.TextStyle | RN.ImageStyle ? true : false
```
Both are `true` 😱 

I'm not exactly sure why this happens and I've failed to prune this type `RN.ViewStyle | Animated.WithAnimatedValue<StyleProp<RN.ViewStyle>>` from the `Animated` part. I believe that if we manage to remove it with conditional types then this would type-check like expected.

This is still somewhat surprising to me because we can also observe this:
<img width="665" alt="Screenshot 2020-08-18 at 14 36 31" src="https://user-images.githubusercontent.com/9800850/90513784-78eb0680-e160-11ea-98ea-0b919e84e737.png">
but the error is not reported.

I'm afraid that I don't know how to fix this right now.

**Comment by efoken** [comment]
@Andarist This somehow works now 😄

**Comment by Andarist** [comment]
Let's close it then and pretend that nothing has happened 😉
