### ISSUE TITLE
ForwardRef issue in @emotion/core 10.0.35

### ISSUE THREAD

**Issue by zslabs** [emotion-js/emotion#1976]
**To reproduce:**

1. Pull-down https://github.com/gremlin/chaoskit
2. Run `yarn develop` (will install all deps and start up Storybook).
3. Upgrade `@emotion/core` to latest `10.0.35` version and attempt to run `yarn develop` again.
4. Storybook will not start, and renders error in console:

<img width="1347" alt="Screen Shot 2020-08-18 at 11 55 45 AM" src="https://user-images.githubusercontent.com/1018402/90536248-c740db00-e149-11ea-9898-ef0b6c4bc394.png">

I believe https://github.com/emotion-js/emotion/commit/2cf3b16b94eb7bad8d745b135fb2bfa99154980d was the only commit for this latest version, so I wonder if there's something within that causing this issue.

**Expected behavior:**

Storybook should run as normal in development-mode.

**Environment information:**

- Please reference repo provided.

**Comment by Andarist** [comment]
Right - this should be the only change between those versions. Could you confirm that `.34` is working fine for you? I find it really weird that this has broken things so spectacularly, but everything is possible. I will look into this in the evening but can't do it right now. Hope this didn't affect too many people - our test suite has passed 🤔

**Comment by zslabs** [comment]
@Andarist Thanks for the quick response as always! Yep `.34` is working fine.

**Comment by Andarist** [comment]
You have ended up with 2 copies of `@emotion/core` and for some reason (I don't have energy to track it) the wrong context was provided (or maybe rather - default value of one of those copies of emotion context was consumed). It somehow has happened because Storybook depends on Emotion as well.

The fix is easy in this case - just run `npx yarn-deduplicate yarn.lock`. Not sure how to handle this better on our side - those things just happen from time to time. In v11 we've introduced [a warning about it](https://github.com/emotion-js/emotion/blob/908a264cf035ab93b89281a5591d2ff37a7a2230/packages/react/src/index.js#L10-L28) but when I think about it now - we probably should change the global key to include the current major version. It should be possible in the future to run a hypothetical Emotion@12 app when using Storybook based on Emotion@11 (it now uses v10).

**Comment by zslabs** [comment]
Thanks, appreciated as always!
