### ISSUE TITLE
This selector does not work, is this intended? `:not(pre) > code`

### ISSUE THREAD

**Issue by kuworking** [emotion-js/emotion#2020]
While using the playground present in @emotion docs, if I try this I cannot get it to work (neither in my site)

```jsx
/** @jsx jsx */
import { jsx, css } from '@emotion/core'

const paragraph = css`
  color: turquoise;

  a {
    border-bottom: 1px solid currentColor;
    cursor: pointer;
  }
  
  :not(pre) > code {
   color: #fff;
   background: #ccc;
   }
`
render(
  <div css={paragraph}>
    Some text.
    <a>A link with a bottom border.</a>
    <p>
      <code>test</code>
    </p>
  </div>
)
```

If I relax the specifity with

```diff
(-)  :not(pre) > code {
(+)  :not(pre) code {
```

then it works, but it should work also in the first case

Is that intended? Or maybe I'm being wrong in thinking that rule should apply?

![image](https://user-images.githubusercontent.com/4474004/93661641-9a8a2700-fa59-11ea-8000-ff4750cf1a04.png)
![image](https://user-images.githubusercontent.com/4474004/93661645-a1b13500-fa59-11ea-935a-f728ce3780fb.png)

**Comment by Andarist** [comment]
You are looking for this:
```diff
```

**Comment by kuworking** [comment]
> You are looking for this:
> 
> ```diff
> const paragraph = css`
>   color: turquoise;
> 
>   a {
>     border-bottom: 1px solid currentColor;
>     cursor: pointer;
>   }
> 
> -  :not(pre) > code {
> +  & :not(pre) > code {
>     color: #fff;
>     background: #ccc;
>   }
> `;
> ```
> 
> All "orphaned" pseudos are prepended automatically with `&` so your version was equivalent to `&:not(pre) > code`.

I already tried, it is not working for me

![image](https://user-images.githubusercontent.com/4474004/93844775-a1ee4200-fc9e-11ea-934a-dc9daedea5a3.png)

The part `css` should be styled when I'm using 

```
& :not(pre) > code {
    color: #fff;
    background: #ccc;
  }
```

But it is not, it only gets styled if using

```
  :not(pre) code {
    background-color: ${props => props.theme.color_vibrant_orange_violet};
    color: #ffffff;
  }
```

Tested with any combination (`& `, `&`, ``) without making any difference

![image](https://user-images.githubusercontent.com/4474004/93844889-06a99c80-fc9f-11ea-9981-6d53b7976e30.png)

**Comment by kuworking** [comment]
Actually if you literally test the code of the original question in a playground of the @emotion docs webpage, you can see the utilization of `& ` doesn't work (at least in my hands)

**Comment by Andarist** [comment]
It works correctly: https://codesandbox.io/s/thirsty-blackburn-75m8i?file=/src/App.js , but I've recognized the problem with the playground. Styles on the playground are processed with our Babel plugin which has a bug and it incorrectly removes this meaningful whitespace. I've fixed it already [here](https://github.com/emotion-js/emotion/pull/1836/files#diff-2c4f56fb9947e4c1a8fa8e37ce1aa261R5) but the fix is only available in the upcoming Emotion 11. 

You can either upgrade to Emotion 11 which is super stable and already used in production at scale - we only have a single issue to solve before we release RC. Or you can trick our Babel plugin by, for example, doing this:
<img width="756" alt="Screenshot 2020-09-22 at 08 19 17" src="https://user-images.githubusercontent.com/9800850/93849488-8be77e00-fcac-11ea-88c7-c23c9ae53c6a.png">

**Comment by kuworking** [comment]
Aah that makes sense, I recently started to use the plugin and I was surprised to see this error in my styling, thinking "but since when this is not working? I thought I got this covered"

Thanks a lot for the fast answering, support in @emotion is top notch 🙌🙌
