### ISSUE TITLE
createPortal and emotion in a gatsby site is not working

### ISSUE THREAD

**Issue by kuworking** [emotion-js/emotion#2038]
I am opening this issue as a duplicated one I've just posted in `gatsby`, since I don't know where it belongs

I think it is a gatsby issue, but I'm opening this one just to be sure

Here https://github.com/gatsbyjs/gatsby/issues/27352 I am using `createPortal` as seen here 
- https://stackoverflow.com/a/34744946/826815
and in the linked codesandbox
- https://codesandbox.io/s/react-iframe-examples-forked-jsn98?file=/src/examples/with-emotion.js

And when embedded in `gatsby`, it works in `gatsby development` but not in `gatsby build `

This happens with and without the `@emotion` plugins

```
  "plugins": ["emotion", "@babel/plugin-proposal-class-properties"]
```

So I'm not sure who is responsible, whether gatsby or emotion 😅

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

I understand that you have already created a codesandbox but it doesn't showcase the problem you are facing, the codesandbox is using CRA while you are facing issues with Gatsby, etc. Please provide a repro case as close as possible to the issue you are facing.

**Comment by kuworking** [comment]
Sorry I didn't mention, in the Gatsby issue there is a minimal repo 

https://github.com/kuworking/createPortalGatsbyBug

A clone, yarn and gatsby develop vs gatsby build and serve should show what I am saying

**Comment by Andarist** [comment]
Weird, but I can't quite repro this using the provided repository. I've done `npm run build && npm run server` + added basic console.logs and I got this:
<img width="579" alt="Screenshot 2020-10-13 at 21 46 04" src="https://user-images.githubusercontent.com/9800850/95908615-94a80d00-0d9d-11eb-844c-f37a099ec1da.png">

**Comment by kuworking** [comment]
```bash
git clone https://github.com/kuworking/createPortalGatsbyBug.git
yarn
gatsby develop (or npm run develop)
```

and I see this at `http://localhost:8000/`

![image](https://user-images.githubusercontent.com/4474004/95940967-e96c7780-0ddf-11eb-8ab9-8eecc2c23d93.png)

And then

```bash
gatsby build (or npm run develop)
gatsby serve (or npm run serve)
```

and I see what you see at `http://localhost:9000/`

![image](https://user-images.githubusercontent.com/4474004/95941014-07d27300-0de0-11eb-812e-36211749b5dc.png)

So the styles are preserved in `gatsby develop`, but not in `gatsby build`

**Comment by Andarist** [comment]
Oh, I've focused on the iframe and not on the main page itself 🤦 The fix is simple - just add a custom `key` option when creating that custom cache. We've already added an error about this in the upcoming Emotion 11:
https://github.com/emotion-js/emotion/blob/ff4ee9d1623c2ad15a6ce9fa7a81ee8809683dad/packages/cache/src/index.js#L48-L53

This happens because the development workflow doesn't use SSR and at the time of cache creation there are no style elements on the page, however when you are using SSR there are already style elements there and because the same default cache key has been used for both the builtin and custom caches they fought over those elements and the second cache created (the custom one) moved those style elements into the iframe and thus removing them from the main page and leaving it unstyled.

**Comment by kuworking** [comment]
Oh great, it does work, thanks a lot 👍👍👍

**Comment by 1-800-jono** [comment]
How to add a custom key option?
