### ISSUE TITLE
Why using CRA with emotion does not generate css bundles?

### ISSUE THREAD

**Issue by dpyzo0o** [emotion-js/emotion#2092]
**Current behavior:**

I'm trying emotion with CRA and I'm using the CSS prop from emotion. After I build the project and view it in the browser, the chrome inspector shows that the styles added by emotion are constructed stylesheet, as shown in the screenshot.

<img width="251" alt="l2lpI" src="https://user-images.githubusercontent.com/24768249/98924901-56267f00-2510-11eb-84ce-7d165331f73c.png">

Normally when we work with CRA it will output CSS bundles, but with emotion, I couldn't find the CSS bundles. Can someone explain to me why this happened?

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 10.1.1

**Comment by Andarist** [comment]
This is how Emotion (and many other CSS-in-JS libraries) works - we are generating styles at runtime (if you are using SSR then some might be generated then) and we inject them to CSSOM directly. There are never external stylesheets involved when working with Emotion.

**Comment by dpyzo0o** [comment]
@Andarist Thanks for the clarification. Does it mean my js bundles will increase?

**Comment by Andarist** [comment]
Yes - somewhat, but at the same time if you code-split your app you might actually downsize the overall impact on your bundlesizes because usually if you are using an external stylesheet then you load all of your rules at once but if you are using a library like Emotion you can make it much easier to only load what is being actually used (by just using JS code-splitting techniques).

**Comment by dpyzo0o** [comment]
@Andarist Thanks!
