### ISSUE TITLE
Storybook - emotion-babel-plugin don't work

### ISSUE THREAD

**Issue by Alecell** [emotion-js/emotion#2126]
**Current behavior:**

We add the emotion babel plugin and it don't work, it only appear the message: `You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop).`

But when add the `@emotion/babel-preset-css-prop` it work as expected.

**To reproduce:**

Create a fresh storybook app and try to add `@emotion` to the project and add the `@emotion` to the plugins.

**Expected behavior:**

It should parse the `css` and show the styled tag when run storybook.

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 11.1.1
- `@emotion/babel-plugin` version: 11.0.0
- `@emotion/babel-preset-css-prop` version: 11.0.0

**I didn't provide a repo just because it seems easier to see what's happening just starting a new `storybook` project and add `emotion` to get the issue.**

The only solution I found that works was [this answer](https://github.com/storybookjs/storybook/issues/7540#issuecomment-675230327) that don't use the plugin, but does the job. The point is, since I found [this stackoverflow answer](https://stackoverflow.com/questions/61741076/css-emotion-library-getting-css-props-error-when-using-css-prop#answer-64013005) that said the plugin has a bunch of features that the preset doesn't, I believe is much better use the plugin if possible.

**Comment by billyjanitsch** [comment]
>I didn't provide a repo just because it seems easier to see what's happening just starting a new storybook project and add emotion to get the issue.

Usually, it's much easier for a maintainer to diagnose the issue if you can provide a repo with the exact conditions replicated. Sometimes the issue is due to a transitive dependency, Node/npm version, package version difference, etc., so it's useful for everyone to have the same reference. (For example, you don't mention which version of Storybook is used, so maybe when I try to repro this with a different version, I'll get a different result.)

If the setup is easy to replicate like you say, then it shouldn't take long to create a new repo, run the setup, push it to GH, and link it here. Then everyone can run the same thing and it's less work for the maintainers. 🙂

**Comment by Andarist** [comment]
☝️ 💯

**Comment by Alecell** [comment]
I'm really sorry, I forgot to close the issue, when I wrote this I didn't realize that when use only the plugin I need the jsx comment, I'll close this.
