### ISSUE TITLE
You have tried to stringify object returned from `css`

### ISSUE THREAD

**Issue by mverissimo** [emotion-js/emotion#2135]
**Current behavior:**

I'm using the `css` prop, and I noticed an error on bundled(dist) files.

```
function _EMOTION_STRINGIFIED_CSS_ERROR__() { return "You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop)."; }
```

This return the error:

```
const baseStyle = () => css`
  label: button;

  display: block;
`;

const ButtonBugElement = styled("button")(baseStyle);

const ButtonBug = forwardRef(({ ...props }, ref) => {
  return <ButtonBugElement ref={ref} {...props} />;
});
```

This don`t:

```
const baseStyle = ({ theme }) => css`
  label: button--bug;

  display: block;
  color: ${theme.colors.red};
`;

const ButtonElement = styled("button")(baseStyle);

const Button = forwardRef(({ ...props }, ref) => {
  return <ButtonElement ref={ref} {...props} />;
});
```

The only difference is the `params` on `baseStyles`, I do some mistake?

Another thing is when I bundle the package with rollup I receive the warning:

```
ui: (!) Unused external imports
ui: jsx imported from external module '@emotion/react/jsx-runtime' but never used
```
But I think this is normal because the the babel config:
`importSource: "@emotion/react",`

**To reproduce:**

1. clone [repo](https://github.com/mverissimo/emotion-bug)
2. yarn setup
3. yarn build
4. check the bundled files into `ui` package

**Expected behavior:**

No errors.

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 11.1.1

**Comment by Andarist** [comment]
This is not a bug - it's not an error. It's just an error ready to be printed **if** end up misusing the result of `css`. Why it doesn't happen for one of the cases? Because those styles are dynamic and can't be computed at build time but the very same `toString` property gets attached to it at runtime in dev mode:
https://github.com/emotion-js/emotion/blob/1ee34005a5e02c9041b36f73395700f1965388eb/packages/serialize/src/index.js#L387-L389

As to this:
> ui: jsx imported from external module '@emotion/react/jsx-runtime' but never used

You shouldn't be using `@babel/preset-react` with `importSource` option together with `@emotion/babel-preset-css-prop`. This preset is only required if you intend to use the **classic** runtime - if you are using the automatic one then just use `@emotion/babel-plugin`.

**Comment by mverissimo** [comment]
Thanks, @Andarist, I think to get it now! I was a little confused about this.
