### ISSUE TITLE
@emotion/core is it possible using checked in emotion js?

### ISSUE THREAD

**Issue by joon-ryencatchers** [emotion-js/emotion#2211]
I want to use checked selector in emotion but it does not work 
Is anyone have solusion?

```
/** @jsx jsx */
import { css, jsx } from '@emotion/core';

const checkbox = () => {
  return(
    <label css={[checkbox]}>
      <input 
       type="checkbox"/>
   </label>    
  )
}

const checkbox = css
  &:first-child + &:checked {
    background: #17a2b8;
  }
;
```

**Comment by Andarist** [comment]
It's possible but you have a problem in your CSS - you shouldn't be targeting a sibling of the first-child but rather the first-child itself.

There are numerous caveats with pseudo-selectors because they might not sometimes do what you think they should - there are existing issues about that with the issues explained. I encourage you to look for them.
