### ISSUE TITLE
theme context not working with styled components in jest

### ISSUE THREAD

**Issue by coltonehrman** [emotion-js/emotion#2351]
*I am upgrading to emotion v11*

I am getting errors in my unit tests indicating that the `theme` context is not provided properly, it is just an empty object `{}`

**Sample render util**
```
import { Router } from 'react-router-dom'
import { render } from '@testing-library/react'
import { createMemoryHistory } from 'history'
import { ThemeProvider } from '@emotion/react'
import theme from '../src/theme'

function renderWithRouterAndTheme(ui, { route = '/', ...renderOptions } = {}) {
  const history = createMemoryHistory({ initialEntries: [route] })
  const utils = render(
    <ThemeProvider theme={theme}>
      <Router history={history}>{ui}</Router>
    </ThemeProvider>,
    renderOptions,
  )
  return {
    ...utils,
    history,
  }
}
```

**Sample test case**
```
test('will render without error', () => {
  const { container, getByText } = renderWithRouterAndTheme(
    <Component {...data} />,
  )
})
```

**Sample component**
```
import styled from '@emotion/styled'
import { Link } from 'react-router-dom'
import { Box } from '../box'

const StyledComponent = styled(Box)`
  ...
  background-color: ${props => props.theme.colors.secondary.greylight};
  ...
`

const App = (props) => {
  ...

  return (
    <StyledComponent />
    ...
  )
}
```

**Comment by iChenLei** [comment]
https://github.com/emotion-js/emotion/blob/main/packages/react/src/theming.js

ThemeContext is just a simple React `Context`, maybe a small reproducation github repo is more helpful for us to debug, thanks.

**Comment by coltonehrman** [comment]
> https://github.com/emotion-js/emotion/blob/main/packages/react/src/theming.js
> 
> 
> 
> ThemeContext is just a simple React `Context`, maybe a small reproducation github repo is more helpful for us to debug, thanks.

Unfortunately, I will not be able to provide anything like that as the code base I am working on is private and has some custom tooling/packages involved.

I can try to reproduce any bits that would be helpful to debug, such as the jest, babel, and we pack configs involved.

I have a hunch it is babel config related but cannot seem to narrow down exactly what config works or why. I was hoping to maybe get some insight into what dependencies emotion requires for the theme context to work properly, or what could be causing it behave strangely.

**Comment by iChenLei** [comment]
![2021-04-16 09 57 58](https://user-images.githubusercontent.com/14012511/114960735-3b2eb100-9e9a-11eb-9b3b-710c3c14cbf4.png)

If you are a vscode user, you can create a simple `javascript debug terminal`, and then run `npm run jest` in this ternimal. Add breakpoint on the code line where is `${({ theme }) => theme.inViewStyle()}`. this first question we need to solve is that `theme object we get is what?` at unit test runtime.

**Comment by coltonehrman** [comment]
> ![2021-04-16 09 57 58](https://user-images.githubusercontent.com/14012511/114960735-3b2eb100-9e9a-11eb-9b3b-710c3c14cbf4.png)
> 
> 
> 
> If you are a vscode user, you can create a simple `javascript debug terminal`, and then run `npm run jest` in this ternimal. Add breakpoint on the code line where is `${({ theme }) => theme.inViewStyle()}`. this first question we need to solve is that `theme object we get is what?` at unit test runtime.
> 
> 

This sounds useful, let me play around with it a bit and see what all I discover.

The 'theme' object is always just an empty object by the way '{}'

**Comment by coltonehrman** [comment]
Update on this.

I tested with using `useTheme` hook from `@emotion/react` and passing the theme down to the `styled` component directly and it worked.

So, it seems like the `styled` component from `@emotion/styled` may have a qwerk in it where it doesn't consume the theme context properly in certain situations.

Below is a code snippet of what I tested with, please refer to comments above to see what I had previously

```
import styled from '@emotion/styled'
import { useTheme } from '@emotion/react'
import { Link } from 'react-router-dom'
import { Box } from '../box'

const StyledComponent = styled(Box)`
  ...
  background-color: ${props => props._theme.colors.secondary.greylight};
  ...
`

const App = (props) => {
  ...
  const _theme = useTheme()

  return (
    <StyledComponent
      _theme={_theme}
    />
    ...
  )
}
```

**Comment by coltonehrman** [comment]
I have dug into this a bit and found that my project includes a `styled-base` package which appears to use `ThemeContext` from `@emotion/core` instead of `@emotion/react`

<img width="1696" alt="Screen Shot 2021-04-16 at 12 35 30 PM" src="https://user-images.githubusercontent.com/12456288/115062805-5f958800-9eb0-11eb-8c09-e69401b77656.png">

Not sure why this package is here, as it appears to have been replaced by `styled/base` here https://github.com/emotion-js/emotion/blob/6c4a9e50f177900f54f7b3368a55b1a7d5e3c002/packages/styled/src/base.js

**Comment by iChenLei** [comment]
`@emotion/react`and`@emotion/core(deprecated)` is different npm package, please upgrade `@emotion/core` to `@emotion/react` every where.
Why rename this package? look this issue https://github.com/emotion-js/emotion/issues/1883 for detail and this official RFC https://github.com/emotion-js/emotion/issues/1635 about `Package renaming `.

Anyway, `@emotion/react`'s React context and `@emotion/core`'s React context is not a same `context`, so you can't use `@emotion/react`'s `useTheme` hook to access `@emotion/core`'s ThemeContext. That's all.

**Comment by Andarist** [comment]
Yep, this means that for some reason your dependency tree is wrong and you load separate versions of our libraries.

**Comment by coltonehrman** [comment]
I was able to finally resolve this by using the babel-macro libs
See - https://emotion.sh/docs/babel-macros

So, I assume the issue lied within my app's babel/webpack configs across dev and test environment.

Anyways, thanks @iChenLei and @Andarist for your input and help :)

**Comment by santosh1997** [comment]
@iChenLei @Andarist 

I'm facing the same issue right after upgrading the jest version to 29
`theme` prop in the `styled` component is passed with empty object `{}`
Not sure how would `babel-macros` be a solution?
Can anyone help me on this?

**Comment by oleksandr-danylchenko** [comment]
### I hit the same issue yesterday using the following app structure:
![image](https://github.com/emotion-js/emotion/assets/68850090/b49686ac-9a25-457c-b9a4-74a1fc8261ef)

For some reason, within the library, the `theme` returned from the `useTheme` contained a fully populated object. But the `theme` in the `css` callback was `{}`  🤷🏻‍♂️ 

Here's what I found on the styles serialization debugging:
![image](https://github.com/emotion-js/emotion/assets/68850090/5a9a08d7-49bc-4ad6-8881-a93fb4f8a83b)

---

Then I checked the bundle of the library I found that it has its own instance of `ThemeContext`, unrelated to the parent app❗
![image](https://github.com/emotion-js/emotion/assets/68850090/13031efd-2704-4c0b-bb85-3935e6ff710a)
So on serialization of the lib styles, `@emotion` was using that distinct empty instance to populate the `theme` in the `css` callback! 

---

But why did the `useTheme` work though? That's because the `useTheme` was imported from the `@emotion/react` package. And under the hood - `useTheme` was using the populated `ThemeContext` of the parent app! 
![image](https://github.com/emotion-js/emotion/assets/68850090/eb498926-aab9-429b-b3f9-83b5e4142432)
https://github.com/emotion-js/emotion/blob/6e0e3880e2366dc4d14c293acac851fc73be730f/packages/react/src/theming.js#L6-L11

---

Combining that:
![image](https://github.com/emotion-js/emotion/assets/68850090/88f792a4-849a-46a2-8685-dfd16f26f3df)

---

The solution I found for now is to mark all the `@emotion` dependencies as external for the library!
![image](https://github.com/emotion-js/emotion/assets/68850090/e4d859d3-9547-4455-878c-8765d20c3b68)

In that way, the parent app is now a single source of truth for the `ThemeContext`!

**Comment by AnsonH** [comment]
Thanks @oleksandr-danylchenko for the detailed investigation 👍 

For my case, solving the below warning that I saw in the console solved the theme context issue:

> You are loading `@emotion/react` when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.

I'm using Create React App, so [this solution](https://github.com/emotion-js/emotion/discussions/2795#discussioncomment-10315541) worked for me. Check out other solutions in that thread for other bundlers.

---
My case is similar to @oleksandr-danylchenko's case, where I have a "Main App" and "Component Library":

Component Library `package.json`:
```json
{
  "dependencies": {
    "@emotion/styled": "^11.11.0",
  }
}
```

Main App `package.json`:
```ts
{
  "dependencies": {
    "@emotion/styled": "^11.9.3",
    "my-component-library": "^0.1.0",  // My Component Library
  }
}
```

Since my component library is using a different Emotion version than my main app, it caused two versions of Emotion being installed in my Main App.
