### ISSUE TITLE
ReferenceError: 'window' is not defined at... var globalContext = isBrowser ? window : global;

### ISSUE THREAD

**Issue by vladop** [emotion-js/emotion#2455]
Very simple. I can this error `ReferenceError: 'window' is not defined` at line: `var globalContext = isBrowser ? window : global`  when **rendering on server**. window object does not exist on server so error is thrown.  Rendering on client works fine!

So check on window object should be made!

- `react` version: 16.0.0
- `@emotion/react` version: 11.4.1

**Comment by GoldenTK** [comment]
I encountered many errors while rendering by SSR using snowpack.

`ReferenceError: window is not defined
    at eval (/_snowpack/pkg/@emotion.react.v11.4.1.js:576:37)
    at initializeModule (/Users/admin/gitRepos/crypto-ssr/node_modules/snowpack/lib/cjs/ssr-loader/index.js:140:13)`
    
 `ReferenceError: document is not defined
    at Object.createCache [as default] (/_snowpack/pkg/@emotion.cache.v11.4.0.js:187:21)`
    
    is it production ready?

**Comment by Andarist** [comment]
As far as I know, Snowpack is primarily targeting web environments and its default settings target that. You should configure it to load files for node, instead of a browser. I'm unsure how to do that though - this is a question for the Snowpack team. You might find an answer in their docs somewhere - or u might want to look through issues in their repo.

As to the OP: Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.
