### ISSUE TITLE
When are styles removed by the caching system?

### ISSUE THREAD

**Issue by shahrouzz** [emotion-js/emotion#2473]
I can't find anything about when styles are considered unused and removed by the caching system.

It is seems very easy to write components that add styles to the DOM that are never removed.

example:
```js
function Foo() {
  const [counter, setCounter] = React.useState(0);
  React.useEffect(() => {
    setInterval(() => {
      setCounter((p) => p + 1);
    }, 1000);
  }, []);
  return (
    <div
      css={css`
        z-index: ${counter};
      `}
    >
      {counter}
    </div>
  );
}
```

This will add an infinite amount of <style> element into <head> of the DOM.

What is the correct way of using emotion so this doesn't happen?

**Comment by Andarist** [comment]
Scoped css rules are never removed (unless you flush the whole cache manually). Global styles may be removed when you unmount `<Global/>`.

The correct way of using Emotion for cases like this is... not using Emotion for them:
```jsx
  return (
    <div
      style={{
        zIndex: counter,
      }}
    >
      {counter}
    </div>
  );
```

**Comment by shahrouzz** [comment]
Is there any usage pattern where emotion cleans up the styles that it has created without the user manually flushing the cache?

It seems odd to me that styles keep accumulating in the DOM. 

What happens on long running apps where different react components keep getting loaded in and out?

**Comment by Andarist** [comment]
The assumption is that you might still need those styles at some point when using the app. This is how most of the CSS-in-JS works. 

Also note that removing styles can actually be expensive and leaving them in the document is (most of the time) rather cheap. Some context can be found here: https://twitter.com/ElliottZ/status/1422360539351629826

**Comment by shahrouzz** [comment]
Ok that clears things up for me.

Thanks.

**Comment by jonenst** [comment]
Hi, first of all thanks a lot for your time and this project.

From what I understand, it should be possible to implement cleanup of unused styles in @emotion/styled (only impossible for @emotion/css, I guess that's what https://github.com/emotion-js/emotion/issues/488#issuecomment-349508337 is talking about) using some kind of refcount system. So it's a choice (mainly based on technical points about performance yes, but a choice nonetheless).

I think the docs should be more clear about this choice (list all technical advantages and disadvantages) ?

Also, maybe the technical performance considerations don't hold in all cases, so it would make sense to allow users to opt-in to style cleanups? If so, are there people interested in implementing this?

If not, maybe just expose enough API so that wrapping projects (e.g. MUI V5) can implement it if they want ? Or maybe the current API already allows a wrapping project to implement this ?

Note: mui v4 had a refcount system over jss's API in their attach/detach functions: https://github.com/mui/material-ui/blob/a1b591aadb56cd829f5800c5c9987134f84644b9/packages/mui-styles/src/makeStyles/makeStyles.js#L128 . But in v5 they support both emotion and styled-components, so maybe implementing the cleanup system was just harder for them ?
