### ISSUE TITLE
making useTheme function generic

### ISSUE THREAD

**Issue by mymoto23** [emotion-js/emotion#2537]
**The problem**

Existing ```useTheme``` function is not compatible with Typescript. 

According to the [docs](https://emotion.sh/docs/typescript#define-a-theme), we have to declare our own types, but could this be more user-friendly?

**Proposed solution**

Making ```useTheme``` function generic might help, so that users can define their own themes and use them without type errors.

for example,

`export function useTheme<T = {}>(): T;`

imo, this way theme can be type safe & be user-friendly as it has a default empty type.

**Comment by iChenLei** [comment]
Relative PR https://github.com/emotion-js/emotion/pull/2352
Relative existing issue https://github.com/emotion-js/emotion/issues/2452 and https://github.com/emotion-js/emotion/issues/2123

**Comment by Andarist** [comment]
I think the opinion expressed [here](https://github.com/emotion-js/emotion/pull/2352#issuecomment-821769442) stands. This won't ever be type-safe - by not allowing that we actually increase the type-safety (a little bit, because if you forget to use ThemeProvider at all then nothing will help that). 

If one decides to ignore this - then OK, you can create your own `useTheme` by casting it to a generic version of your choosing. We just don't make this easier because we believe that it can be a footgun.
