### ISSUE TITLE
font-icon requires escape

### ISSUE THREAD

**Issue by andrei9669** [emotion-js/emotion#2538]
**Description:**
in order to use font-icons, like `\f123`, you have to double escape like this `\\f123`
as in [this example](https://codesandbox.io/s/rough-wind-w9s31?file=/src/index.tsx), you can see that `\\f559` works but `\f559` doesn't work. 

I'm not sure if it is a documentation issue, because I couldn't find anything about this, or a bug.

This confused me because with styled-components, `\f559` works fine

**Comment by Andarist** [comment]
I'm unsure why this works with `styled-components` but it makes sense that you need to escape this twice. The problem is that when writing CSS-in-JS you are first giving your styles to the JS parser and then the resulting output it given to CSS.

If you consider what happens under the hood then the single-escape variant **shouldn't work** because in this string: `\f123` the `\f` is just interpreted by JS as form feed character. You can check this out if you try to decompose this into char codes:
```js
[...'\f559'].map(c => c.charCodeAt(0)) // [12, 53, 53, 57]
```
What we want here is to **preserve** the `\f` as a string so it can be interpreted correctly by the CSS. Let's compare the char codes when we do that:
```js
[...'\\f559'].map(c => c.charCodeAt(0)) // [92, 102, 53, 53, 57]
```

If you think this is not explained well in the docs then I encourage you to prepare a documentation PR

**Comment by andrei9669** [comment]
huh, your explanations makes sense and it really is interesting as to why/how it works with styled-components.

**Comment by Andarist** [comment]
It turns out that Styled Components are still using Stylis v3 and there was an "auto fixup" code there for this issue:
https://github.com/thysultan/stylis.js/blob/4561e9bc830fccf1cb0e9e9838488b4d1d5cebf5/stylis.js#L625-L628

Once they migrate to v4 this would stop working with SC as well.

**Comment by andrei9669** [comment]
Oh, cool. Thank you for the information
