### ISSUE TITLE
emotion cache is not using the right key, when using directly @emotion/css

### ISSUE THREAD

**Issue by caub** [emotion-js/emotion#2607]
**To reproduce:**

It's a bit a corner case, that happens when using  [react-dates](https://github.com/airbnb/react-dates)

Demo: https://codesandbox.io/s/react-datepickers-o9fbh?file=/src/Datepicker.js

```jsx
const cssCache = createCache({
  key: "app"
});
ReactDOM.render(
  <CacheProvider value={cssCache}>
    <DatePicker />
  </CacheProvider>,
  root
);
```

DatePicker can be configured to use emotion, I did this:

```js
import { css } from "@emotion/css";
import ThemedStyleSheet from "react-with-styles/lib/ThemedStyleSheet";
import DefaultTheme from "react-dates/lib/theme/DefaultTheme";

ThemedStyleSheet.registerInterface({
  create(styleHash) {
    return styleHash;
  },
  resolve(styles) {
    return { className: css(styles[0]) };
  },
  flush() {}
});
```
The problem then is that the styles generated by that datepicker doesn't use the cache provider key ('app'), you will see 'css' instead

It becomes an issue when passing a nonce, those generated styles get rejected by the browser

I think I should be using a `css()` function that is bound to the cache, but how can I get it?

- `react` version: ^17
- `@emotion/react` version: ^11

**Comment by Andarist** [comment]
`@emotion/css` is using the default cache (it's configured with `css` key) and you can't change that. You can, however, create a custom emotion instance with `@emotion/css/create-instance` and just configure it with the same cache as the one that you provide through `CacheProvider`:
https://codesandbox.io/s/react-datepickers-forked-94m0j?file=/src/index.js

This is the main reason why `css` from `@emotion/react` **doesn't** return a string that could be used as a class name - it's because it can be called outside of render but outside of render we don't have access to React's context so we can produce reliable class names that would be configured with the correct key, nonce, etc.

**Comment by caub** [comment]
Ok, thanks 👍🏽 perfect

Best end of year
