### ISSUE TITLE
Babel plugin doesn't add PURE comment in latests babel

### ISSUE THREAD

**Issue by paul-sachs** [emotion-js/emotion#2619]
**Current behavior:**

The current babel plugin seems to work fine for everything except the /* #__PURE__ */ comment that should be seen.

**To reproduce:**

1. See custom repo: https://github.com/paul-sachs/emotion-babel-bug
2. Run `npm install` and `npm run build`
3. Output will not have PURE comment prefixed to styled component

**Expected behavior:**

All styled blocks should be prefixed with PURE comment

**Environment information:**

- "react": "^17.0.2",
- "@emotion/babel-plugin": "^11.7.2"
- "@emotion/core": "^11.0.0",
- "@emotion/styled": "^11.6.0",

**Comment by srmagura** [comment]
Thanks for the report. It's odd, [the line](https://github.com/emotion-js/emotion/blob/main/packages/babel-plugin/src/styled-macro.js#L108) that adds the PURE comment is getting hit, but the comment is not actually getting added. I can look at this over the weekend, though I'm not sure if I can fix it.

**Comment by paul-sachs** [comment]
I ended up fixing it with a yarn patch. Basically just did
‘reference.parentPath.addComment(..)’ but I wasn’t sure that was the
correct solution.

**Comment by srmagura** [comment]
Awesome. @Andarist is that the correct solution?

**Comment by Andarist** [comment]
It might be the correct solution but that also means that something has changed on the Babel side of things. In general, comments are really wonky in AST because based on a source file it's really uncertain **to which AST node** a particular comment belongs. So perhaps the Babel generator (from AST to text) changes its logic somehow and what we have been adding became swallowed now?

We should upgrade all Babel deps and check if any of our snapshots change.
