### ISSUE TITLE
TypeError: Cannot read property 'registered' of null

### ISSUE THREAD

**Issue by shertu** [emotion-js/emotion#2786]
I am unsure whether or not this is a bug so I am including it here:

https://stackoverflow.com/questions/72681421/react-with-emotion-npm-package-gives-typeerror

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.9.3

**Comment by gjhenrique** [comment]
HI @shertu, 

I saw on stackoverflow you disabled SSR, and this was our initial "fix" for this issue in one of our next.js apps. 

The issue for us is that the library, that includes `mui` and consequently `emotion` was using `web` from the `target` option in webpack to generate the bundle. It's the default from webpack, so it's easy to miss.
https://webpack.js.org/configuration/target/

Using this option, webpack removes everything that's on these lines.
https://github.com/emotion-js/emotion/blob/314a5fb08b0f730e7aa88da0c974dfea13cc9b32/packages/react/src/context.js#L44-L67

The fix was to switch to `target: node` in the library instead. By doing it, the final bundle comes with these lines, `emotion` populates the context, and no dangling null is left to explode at any moment.
