### ISSUE TITLE
Compound Component TS signature

### ISSUE THREAD

**Issue by kevinmeyvaert** [emotion-js/emotion#2965]
**Current behavior:**

When assigning compound components, the TS definition of styled() loses context of the compound components.

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-forked-wq7xxn?file=/src/App.tsx

**Expected behavior:**

The newly created styled compound component retains the correct TS signature.

**Environment information:**

"react": "18.2.0"
"react-native": "0.70.6"
"@emotion/native": "11.10.0"
"@emotion/react": "11.10.5"

**Comment by Andarist** [comment]
We don't support hoisting those static properties. It doesn't work at runtime and thus doesn't work at type level either. 

Attaching components like this to functions prevents tree-shaking the unused ones so I don't think that we want to promote this by including support for this feature. You can still use compound components pattern by structuring your values differently (for example, you can assign them on a styled component itself, instead of hoping for "automatic transfer" performed by Emotion, or you can just create a regular JS object with properties, that would be components, instead of a component with extra properties). 

You can also always build a thin layer wrapping our own `styled- with the requested feature and use your own version throughout the app.

**Comment by kevinmeyvaert** [comment]
As it is a commonly used pattern I thought it was weird that there was no support. But as it is an intentional choice I will work around this, no problem. At least, for future reference, people having similar problems will find this issue. :)

Thanks for giving feedback!
