### ISSUE TITLE
Styling descendants on hover

### ISSUE THREAD

**Issue by rstacruz** [emotion-js/emotion#311]
Question: is it possible to style descendant elements based on the "state" of a parent element?

## Example: two components

In this example, I'd like `Button > Title` to look different when `Button` is hovered:

```js
<Button>
  <Title>Click me</Title>
</Button>

const Button = styled.button`
  display: inline-block;
`

const Title = styled.span`
  color: #888;

  /* Note: this doesn't work */
  ${Button}:hover & {
    color: #111;
  }
`
```

## Example: class names

I figured this is best done with CSS classnames, but that doesn't work either:

```js
<Button className={isDark}>
  <Title>Click me</Title>
</Button>

const Button = styled.button`
  display: inline-block;
`

const isDark = css`
  background: #333;
`

const Title = styled.span`
  color: #888;

  /* Note: this also doesn't work */
  .${isDark} & {
    color: #aaa;
  }
  /* Neither does this */
  .${isDark}:hover & {
    color: #fff;
  }
`
```

**Comment by mitchellhamilton** [comment]
The first example is a known problem and will be fixed in #299.

The second example is more complex because emotion combines styles together to make specificity more predictable so the `isDark` class name isn't actually on the `Button` component but instead the `isDark` styles are merged into `Button`'s styles. I would have a dark prop or something like that and style it based on that.
