### ISSUE TITLE
Issues with extractStatic when used with typescript and react-app-rewired

### ISSUE THREAD

**Issue by thupi** [emotion-js/emotion#405]
- `emotion` version: 8.0.5
- `react` version: 16.0.0

What you did:
I tried to get emotion working with my existing typescript project which worked well except that the extractStatic feature didn't do anything.

The project uses a typescript fork of create-react-app and react-app-rewired.

What happened:
The extractStatic flag is ignored. However, the sourcemap flag works as expected.

Reproduction:
https://github.com/thupi/emotion-typescript-poc

Problem description:
The main problem is that the extractStatic feature doesn't work. 
I have not managed to find the reason for the issue.

**Comment by cameron-martin** [comment]
I think this is because TypeScript is compiling the tagged template literals down to function calls because you have "target" set to "es5" in your tsconfig, so the babel plugin (which runs after) is not picking them up. You'll have to set "target" to es2015 or above and then make babel compile down to es5.

Or you could do what I do and use babel 7 beta to compile your TypeScript.

**Comment by thupi** [comment]
@cameron-martin That sounds like something i would want to look more into :-) ! Do you have managed to get that method to work with create-react-app :-) ? I am currently using a typescript fork of create-react-app whch makes it somewhat easier to maintain :-)

**Comment by cameron-martin** [comment]
Which method? Babel 7?

**Comment by thupi** [comment]
Yeah @cameron-martin :-)

**Comment by thupi** [comment]
I just tried to let the typescript compiler target es6 and the use babel to compile to es5 which solves the issue :-) ! 

Thanks :-) I wouldn't have been able to figure that one out :D !

**Comment by cameron-martin** [comment]
Glad I could help.
