### ISSUE TITLE
Styles being inserted twice using SSR strategy.

### ISSUE THREAD

**Issue by SMLMRKHLMS** [emotion-js/emotion#486]
- `emotion` version: 8.0.11
- `react` version: 15.6.1

What you did: Attempting to use the SSR strategy for emotion.

What happened: My styles are being inserted twice even when I call `hydrate(ids)` on the client.
<img width="321" alt="screen shot 2017-12-01 at 5 39 55 pm" src="https://user-images.githubusercontent.com/5240571/33506686-fc705b9a-d6be-11e7-976f-edbb5472ae0c.png">
<img width="470" alt="screen shot 2017-12-01 at 5 54 01 pm" src="https://user-images.githubusercontent.com/5240571/33507067-a989a4b6-d6c0-11e7-8f63-3eed9f8b286a.png">

Not sure what the path forward is since I followed the documentation and there are no differences between my implementation and the implementation within the documentation. Any ideas of things I could be doing incorrectly?

**Comment by mitchellhamilton** [comment]
You're likely calling hydrate after the styles are inserted, this gets complicated with ES imports since you could import some files that insert styles and do a hydrate but the inserted files will run first. To fix this, you can create file that purely calls hydrate and make it the first import.

We're planning on solving this in the next major version with new SSR methods will automatically hydrate.

**Comment by SMLMRKHLMS** [comment]
Thank you! Worked perfectly.

**Comment by AgtLucas** [comment]
I've tried to move the hydrate call to another file and import it, but I'm still having the same issue as @smlmrkhlms was having.

Any ideas?
