### ISSUE TITLE
Slow performance in development mode

### ISSUE THREAD

**Issue by baktiaditya** [emotion-js/emotion#543]
- `emotion` version: 8.0.11
- `react` version: 15.6.1

**What happened:**
I have some performance problems with emotion in development mode. Is there a way to only generate a single `<style />` tag in the head? I use storybook to develop my components, and when hot reloads are running, their performance is getting slower.

I have tried using `sheet.speedy(true)` but then hot reload is not as perfect as it should be. It will reloading whole storybook iframe, not injecting it.

![alt text](https://pbs.twimg.com/media/DTzjCLGVMAAqXlT.jpg:large "problem")

**Comment by fforres** [comment]
Not sure if expected behavior, but cannot seem to hot-reload emotion styles.

If I change some rule, emotion appends new `<style/>` tags, and if I revert my change, Emotion does not inject a new `<style/>` (Or remove the 'now invalid' set of tags it inserted second)

@baktiaditya did you find a solution?

**Comment by fandy** [comment]
@fforres did you manage to figure out hot reloading the styles?

**Comment by bystrovo** [comment]
still current problem
