### ISSUE TITLE
CSS labels with object keys

### ISSUE THREAD

**Issue by JeSuis** [emotion-js/emotion#548]
- `emotion` version: 8 
- `react` version: 16

Relevant code.

**in**
```
styles = {
  dog: {
    color: brown;
    font-size: 1rem;
  },
  cat: {
    border: 2px solid orange;
    margin: 10px;
  }
}
```
**output**
```
css-2352-dog
css-5342-cat
```

What you did:
Created a style object

What happened:

Currently with autoLabel this results in all generated labels having the css label of styles
`css-234324-styles`
So you can't tell what is what.

Problem description:
Migrating over from aphrodite where everything is in style objects.
Turned on autoLabel and was disappointed to see that everything had the label of styled and did not use the names of the keys.
This would be a great amount of manual work.

Suggested solution:
Have an option to use object keys as labels in order to make transitioning much easier and have more flexibility in general.

**Comment by tkh44** [comment]
This feature is documented here. https://emotion.sh/docs/labels#___gatsby

**Comment by mitchellhamilton** [comment]
@tkh44 I think this is referring to auto labeling based on the keys rather than manually adding the keys onto the objects like is shown on https://emotion.sh/docs/labels.

@JeSuis We can't auto label styles that are just on objects like that in babel-plugin-emotion, we could auto label objects with css calls around the objects but what you could do is make a helper function that adds the labels at runtime like this.

```jsx
function addLabels(styles) {
  return Object.keys(styles).reduce((obj, key) => {
    obj[key] = { label: key, ...styles[key] }
    return obj
  }, {})
}

styles = addLabels({
  styleName: {
    color: 'hotpink'
  }
})

```

**Comment by JeSuis** [comment]
@tkh44 @mitchellhamilton is correct, I don't want to have to manually add them to every style.

Thanks!, I'll play with this code.

**Comment by tkh44** [comment]
Sorry about that @JeSuis. Hopefully, @mitchellhamilton's solution works for you.

**Comment by JeSuis** [comment]
So just in case anyone else is interested, this is the helper function we ended up using, it accounts for both css and template literal versions and wraps it in the css call for us.

```
    return Object.keys(styles).reduce((obj, key) => {

        if (typeof styles[key] === 'object') {
            obj[key] = css({ label: key, ...styles[key] });
        } else {
            obj[key] = css(`label: ${ key };` + styles[key]);
        }

        return obj;
    }, {});
```

And so now we wrap our style blocks with the helper and magic happens.

**Comment by mattfysh** [comment]
is there a solution for this, when tagged templates are used?

```
const styles = {
  dog: css`
    color: brown;
  `
}
```

I was going to submit a pull request to let the babel macro support configuration (e.g. autoLabel - more info here https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md#config-experimental) ... but because I use this styles pattern (to avoid polluting local file top-level scope), it looks like I'm not going to be getting semantic class names even when I manage to get `autoLabel` switched on

**Comment by mitchellhamilton** [comment]
@mattfysh We would happily accept a PR to support auto label on objects. It would require checking if the parent node is an `ObjectProperty`  and getting the identifier name from the key.
https://github.com/emotion-js/emotion/blob/7dc03d6fb66fff6190b8cd5635b93eeb092a90da/packages/babel-plugin-emotion/src/babel-utils.js#L7-L30
