### ISSUE TITLE
How to use babel-plugin-emotion with jest ?

### ISSUE THREAD

**Issue by alex-shatalov** [emotion-js/emotion#562]
we are using create-react-app. In test we have error 

```javascript
You are trying to use the styled shorthand without babel-plugin-emotion.
Please install and setup babel-plugin-emotion or use the function
call syntax(`styled('section')` instead of `styled.section`)
```

in package.json configuring jest didn't help

Jest: a transform must export a `process` function.

```javascript
 "jest": {
    "transform": {
      "^.+\\.js?$": "babel-plugin-emotion"
    }
  }

**Comment by TrySound** [comment]
@alex-shatalov https://github.com/emotion-js/emotion/tree/master/packages/jest-emotion

**Comment by tkh44** [comment]
I don't think you can use custom babel plugins with create-react-app. I don't know how any styled.section calls are working without the plugin.

The answer is right in the answer.

> use the function
call syntax(`styled('section')` instead of `styled.section`)

Do not use the `styled.section` syntax if you cannot use the plugin.
