### ISSUE TITLE
injectGlobal leaks accross multiple requests in SSR

### ISSUE THREAD

**Issue by azizhk** [emotion-js/emotion#573]
- `emotion` version: 9.0.1
- `react` version: 16.0.0

Relevant code.

```javascript
injectGlobal`
  html, body {
    font-size: ${[22, 24, 26][Math.floor(Math.random() * 3)]}px;
  }
`
```

What you did:
What I did was something bad just to break and create an example.
I am picking a random number from 22, 24 and 26 and setting the `font-size` of `html,body` to be it.

What happened:
On my first request I got the font with 22px and then my page specific style.
On my second request I got the `html, body {font-size: 24px}` appended after the first request's styles.
On my third request onwards I got `html, body {font-size: 26px}` appended after the second request's styles.

Reproduction:
Clone this:
https://github.com/zeit/next.js/tree/master/examples/with-emotion
and modify:
https://github.com/zeit/next.js/blob/master/examples/with-emotion/pages/index.js
to randomize font-size.

Problem description:
If I want to use a third party component in one page, I would injectGlobal it and then it would come up in other places.

Suggested solution:
Something like a wrapper around ReactDOM.renderToString
```js
const styles = extractCritical(() => {
  return ReactDOM.renderToString(<Page />)
})
```
Where it only gives me the styles injected in the render of <Page />
And extractCritical automatically resets the global styles before and after the function call.

**Comment by azizhk** [comment]
Oh so I found out flush mentioned in https://github.com/emotion-js/emotion/issues/491#issuecomment-352051652 but could not find its documentation. Should have dug deep into the issues first.

Is it not part of the spec or bad practice?
Or do you want documentation written for it?
How to determine something which is going to be used on every page and something to be added globally on the current page?

**Comment by tkh44** [comment]
Try moving the injectGlobal styles out of the component like this PR shows @azizhk 

https://github.com/zeit/next.js/pull/3821/files

**Comment by azizhk** [comment]
How do you recommend we work with third party components which have their own stylesheets?
I have react-select being used on a few pages and am importing it using injectGlobal.
But then it got added in all pages.

**Comment by azizhk** [comment]
Also do you recommend anything for development when we are modifying the values of injectGlobal?
Like every change that I make to injectGlobal value keeps getting appended to the styles.

<img width="622" alt="screen shot 2018-02-16 at 12 59 47 pm" src="https://user-images.githubusercontent.com/5094296/36297557-68edc2b2-1319-11e8-8b58-1ee238540116.png">
/* HTML Beautified for screenshot */

**Comment by azizhk** [comment]
realized that I cannot use flush along with https://github.com/zeit/next.js/pull/3821/files
as any style that were pulled out of the scope don't get created again.

**Comment by mitchellhamilton** [comment]
@azizhk There are two ways I think you could solve this.

1. Don't use `injectGlobal`, use `css` and [react-helmet](https://github.com/nfl/react-helmet) to add the class to the html and body element. (You should probably do this unless you're cool with using experimental stuff)
2. Use [`@emotion/global`](https://github.com/emotion-js/next#global)(you'll also need to install `@emotion/core` and `@emotion/css`) which will render the styles directly in the react tree, avoiding this whole problem. (the warning at the top of the README is mainly warning about breaking changes rather than bugs in the implementation, it's pretty well tested but you should lock the version) It depends on react@16.3(right now just the alpha) so you can use the alpha or install [`create-react-context`](https://github.com/jamiebuilds/create-react-context) and polyfill the new context API like this.
```jsx
// put this in a separate file and make it the first import in your app so that it runs before `@emotion/core`
import React from 'react'
import createReactContext from 'create-react-context'

React.createContext = createReactContext
```
