### ISSUE TITLE
Sever side rendering: `extractCritical` should work on an element tree

### ISSUE THREAD

**Issue by asyncmax** [emotion-js/emotion#579]
- `emotion` version:
9.0.2
- `react` version:
16.2.0
Relevant code.

```javascript

```

What you did:

What happened:

Reproduction:

Problem description:

Currently, `extractCritical` works only on the string output of React's `renderToString`. This effectively negates the benefit of React's new API `renderToNodeStream`.

I know there is a separate API `renderStylesToNodeStream` for streaming, but it is not as efficient as `extractCritical` in production.

Suggested solution:

`extractCritical` should support an element tree instead of string as `collectStyles` of `styled-components` does.

**Comment by mitchellhamilton** [comment]
[Having an API like `collectStyles` wouldn't help, collectStyles in styled-components still requires `getStyleTags` or `interleaveWithNodeStream` which is similar to `renderStylesToString` and `renderStylesToNodeStream` respectively.](https://www.styled-components.com/docs/advanced#server-side-rendering) Having an element tree isn't useful since we would have to render the tree ourselves which would mean rendering everything twice. [In styled-components,` collectStyles` just adds a provider component](https://github.com/styled-components/styled-components/blob/81f1a20019eb6b2a6de9fe6d6a1882638c1183b1/src/models/ServerStyleSheet.js#L43).

Could you explain what you mean by `renderStylesToNodeStream` not being as efficient as `extractCritical`?

**Comment by asyncmax** [comment]
I didn't know the implementation details of `collectStyles` and assumed it would create a lighter version of element tree, independent from `renderToString`, which was clearly wrong. Thank you for pointing out.

I still believe having an `extractCritical`-like API, working on the element tree directly rather than depending on the string output of `renderToString` can provide better performance by eliminating overhead of stringifying the result. For that matter, `react-prepare` can be an example of custom construction of the element tree.

The reason I believe `reanderStylesToNodeStream` is not as efficient as `extractCritical` is because, if I understood correctly, it re-inserts all the style rules that were interleaved in the markup on the client side. Also, I am wondering what happens to the interleaved `<style>` tags when React updates the DOM on the client side. Are they ignored and discarded? Or do they even show up in DOM? Because behavior of `<style>` tags without `scoped` attributes within `body` is not defined in HTML standard, I am wondering if we can safely depend on the behavior independent from browser platforms.

**Comment by mitchellhamilton** [comment]
Styles won't be reinserted on the client, the style tags are moved to the head so they don't interfere with anything. Every major browser allows style tags in the body so I don't think that will be a problem.

Also, rendering and getting the styles for an element tree will be more expensive and slower than getting the styles from a string of html. For rendering an element tree, we would have to render all of the components and then exec some regex on all of the className attributes and then you would have to render all of the components again. With `extractCritical`, you just have to render once and then `extractCritical` does regex execs on the whole html string.

**Comment by asyncmax** [comment]
Fair enough, thanks for looking into it. I'm closing this issue.
