### ISSUE TITLE
Problem with props being ignored with preact

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#581]
- `emotion` version: latest stable
- `react` version: preact latest stable

Relevant code.

```javascript
const Dot = styled('div')`
  background-color: ${props => props.color};
`;

return const Test = () => <Dot color="red" />;
```

What you did:

Ran this with `preact` and `preact-emotion` (also the babel plugin).

What happened:

The `color` property is passed to the HTML element and is not consumed by emotion (the css is empty).

![image](https://user-images.githubusercontent.com/5382443/36851762-5053ef14-1d6a-11e8-8191-c4da291491cc.png)

**Comment by mitchellhamilton** [comment]
We have to pass the color property to the element since it's an HTML attribute someone might want to use. (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes, find the color attribute on this page, it's also an SVG attribute that people might want to use https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color).

By 'the css is empty' do you mean that the `background-color: red;` isn't applied? If so, I can't reproduce that. https://codesandbox.io/s/xp0nv66k3q

**Comment by egoist** [comment]
@mitchellhamilton Is there a way to prevent adding attributes like `color` `width` to the element?

**Comment by mitchellhamilton** [comment]
@egoist You can manually omit them like this

```jsx
const SomeComponent = styled(({ width, color, ...props }) => (
  <div {...props} />
))(...styles);

```
