### ISSUE TITLE
Is there any way to reduce the bundled size of emotion

### ISSUE THREAD

**Issue by xialvjun** [emotion-js/emotion#646]
I'm very happy with the api of emotion v9.

I only use `import { css, cx } from 'emotion';`, I don't use `react-emotion`.

I don't know how big is emotion. But I think it's size is a litter big because `css` can do the prefix at runtime.

So I want to ask the bundled size of emotion. And how can we reduce it, `babel-plugin-emotion`?

**Comment by ChristopherBiscardi** [comment]
emotion 9.1.3 is 5.68kb as shown in the badges on the README.md.

<img width="858" alt="screen shot 2018-06-03 at 8 49 03 am" src="https://user-images.githubusercontent.com/551247/40888370-224aea92-670b-11e8-82e3-13d301815931.png">

Using `css` and `cx` uses nearly all of the code paths in the emotion package so there's probably little to do there to reduce size.

Stylis itself is 3kb, but emotion [already uses a smaller version of it](https://www.npmjs.com/package/@emotion/stylis) too.

For me it's not really worth worrying about 5kb in my application bundles for something I use in basically every component. There are much bigger and easier wins to be had by switching from React to Preact for example, and I would do those first before trying to get emotion any smaller (since it's already pretty small).

**Comment by xialvjun** [comment]
Oh, yeah, didn't see the badge `core gzip size: 5.68kB`...thanks.

**Comment by carpben** [comment]
I too use Emotion in every component. But looking at the bundle analysis, it doesn't look like 5kb. 
I use version 9 of both Emotion and Emotion-React. Looking at the Bundle. 
![image](https://user-images.githubusercontent.com/13496178/56863467-375ca800-69bf-11e9-9d8a-8436545df402.png)
I count a total of 39kb. Am I doing something wrong?

**Comment by nikolay-scaleforce** [comment]
I have even bigger problem:
![image](https://user-images.githubusercontent.com/50861321/61774035-b31f9280-adfe-11e9-82d8-794ee6dbecc8.png)

the usage of css and cx generates files which are huge in term of size - 40-50kb per file .....

**Comment by Fivapr** [comment]
> I have even bigger problem:
> ![image](https://user-images.githubusercontent.com/50861321/61774035-b31f9280-adfe-11e9-82d8-794ee6dbecc8.png)
> 
> the usage of css and cx generates files which are huge in term of size - 40-50kb per file .....

we have same problem, is there any related issue?

**Comment by ericz1803** [comment]
If anyone has this problem in the future and is using babel, make sure [Source Maps](https://emotion.sh/docs/source-maps) are not injected in the production build by setting `NODE_ENV=production` or setting `sourceMap` to `false` in the babel config (https://emotion.sh/docs/babel-plugin-emotion).
