### ISSUE TITLE
cx - replace overwritten styles instead of appending when combined

### ISSUE THREAD

**Issue by leighkendell** [emotion-js/emotion#648]
Hi there, just wondering if there's any way of replacing/removing the original style that's overwritten when combining classes, similar to the behaviour of composition?

i.e.

```
const cls1 = css`
	font-size: 20px;
	background: green;
`
const cls2 = css`
	background: blue;
`

render(<div className={cx(cls1, cls2)}>Blue Text</div>)

// desired output
.css-12345 {
  font-size: 20px;
  background: blue;
}
```

**Comment by mitchellhamilton** [comment]
There's no way that we could do this well because we don't know what is an intentional fallback and what is not. If we could somehow know what is an intentional fallback and what is not, checking whether something is an intentional fallback or not and removing it would likely be worse for performance that appending the styles anyway.
