### ISSUE TITLE
Increasing specificity - overriding CSS

### ISSUE THREAD

**Issue by cosmith** [emotion-js/emotion#712]
Hi, we're in the process of migrating our app to emotion. Up until now we used normal CSS with bootstrap. 
I ran into an issue where I want to style a component but the bootstrap CSS has a higher specificity because of nested rules (in my case I'm trying to style a navbar button).

```
const SidebarSubLi = styled("li")`
    background-color: #0068bf;
`;

const SidebarSubLink = styled(TrackedLink)`
    &:hover {
        background-color: green;
    }
`;
```

![image](https://user-images.githubusercontent.com/1194749/41149307-84fe143a-6b0b-11e8-88ee-016b7c6dac8f.png)

this CSS takes precedence:
```
.navbar-fixed-side.navbar-inverse .navbar-nav .dropdown-menu>li:not(.active)>a:focus, .navbar-fixed-side.navbar-inverse .navbar-nav .dropdown-menu>li:not(.active)>a:hover, .navbar-fixed-side.navbar-inverse .navbar-nav>li:not(.active)>a:focus, .navbar-fixed-side.navbar-inverse .navbar-nav>li:not(.active)>a:hover {
    background-color: #0371ca;
    color: #fff;
}
```

I ran into this for Glamorous: https://glamorous.rocks/examples/#increase-specificity which injects an id on the body to increase specificity of all Glamorous-generated CSS, is there a similar mechanism available with emotion?

Thanks in advance for your suggestions.

- `emotion` version: 9.2.1
- `react` version: 16.2.0

**Comment by Andarist** [comment]
It's possible, but u'd have to create ur own instance of emotion to add a stylis plugin. I've created this plugin for u - https://github.com/Andarist/stylis-plugin-extra-scope . Keep in mind that I have just written it (and written few tests), so it might not work as u expect - however at this moment I have no idea how it could be improved. Try it out and let know if it's working for your use case 😉 

```js
import * as React from 'react'
import createEmotion from 'create-emotion'
import createEmotionStyled from 'create-emotion-styled'
import extraScopePlugin from 'stylis-plugin-extra-scope'

const emotion = createEmotion({}, { key: 'lc', stylisPlugins: [extraScopePlugin('#extra-scope')] })
const { css, cx, injectGlobal, keyframes } = emotion
export { css, cx, injectGlobal, keyframes }

const styled = createEmotionStyled(emotion, React)
export default styled
```

You can then just import those created versions of `styled`, `css`, `cx`, `injectGlobal` & `keyframes` from your module instead of directly importing it from `react-emotion`.

**Comment by epeli** [comment]
I hit this too. I was supposed to make a small SPA to work on top of WordPress admin interface. But it turned out to quite difficult as WordPress admin UI has a lot very global selectors which style plain inputs etc.

@Andarist your plugins seems to work great, thank you!

**Comment by Andarist** [comment]
I guess this issue can be closed then, feel free to comment further though - or create a new issue.

**Comment by eugeneoshepkov** [comment]
@Andarist Works like a charm, thanks! I think it should be put in the emotion docs somewhere since this case might be quite common

**Comment by Firfi** [comment]
What is the recommended way for the newest package versions? 
I'm asking because of the comment https://github.com/emotion-js/emotion/issues/1082#issuecomment-445055378 which assumes create-emotion shouldn't be used ideally. I've also tried the solution in this issue (https://github.com/emotion-js/emotion/issues/712#issuecomment-395912093) and it caused me a similar to aforementioned  https://github.com/emotion-js/emotion/issues/1082 problem.

**Comment by tcjcodes** [comment]
Hi, I'm wondering this as well. I have a similar issue where I'm using a class-based library (Bulma) that I'm trying to migrate over and I'm having a hard time finding solutions for increasing specificity in Emotion

**Comment by Andarist** [comment]
@tcjcodes if you share a runnable repro case I could take a look at your issue

**Comment by DidiBear** [comment]
@Andarist Here is a `CodeSandbox` with the above example:

https://codesandbox.io/s/increase-css-specificity-e8k5u?file=/index.js

You can toggle the line containing `extraScopePlugin`, currently it just breaks all styled components.

**Comment by tcjcodes** [comment]
It's happening in my project but I wasn't able to repro it, which means something's funky with my setup. I'll close this, thanks all!
