### ISSUE TITLE
Font weight 'px' issue

### ISSUE THREAD

**Issue by harmeetjaipur** [emotion-js/emotion#717]
I would first like to say that `emotion` is a great way to write css. I prefer dealing with JS and this is exactly what I needed for my style requirements. Not having to think about coming up with unique class names is a great advantage.

- `emotion` version: 9.1.3
- `react` version: 16.3.2

Relevant code.

```javascript
const tagline = css({
  'font-size': '13px',
  'font-weight': 400,
  'text-transform': 'uppercase',
});
```

I am trying to apply the font-weight of `400` with and without single quotes abut the output always is `400px` which browsers reject.

I am probably missing something silly here. Help is appreciated.

**Comment by Ailrun** [comment]
Thank you for reporting, @harmeetjaipur!
I just investigated codes and I found https://github.com/emotion-js/emotion/blob/21c3308ee6764a04a267ff07e5890a6626603c15/packages/create-emotion/src/utils.js#L16-L23
which related with following package (or rather, repo).
https://github.com/emotion-js/next/blob/master/packages/unitless/src/index.js
The repo does not have any 'hypened-properties`, and that's where the problem came from.

**Comment by Ailrun** [comment]
@mitchellhamilton Could you fix it? Or is there any reason for not to add `'hypened-properties'`?

**Comment by Andarist** [comment]
IMHO when using objects camelCase properties are more natural & it's also how browsers support css properties in most APIs. Supporting both leads to potential ambiguities.

**Comment by harmeetjaipur** [comment]
That worked. I am not sure why I wasn't using camelCase as properties. `fontWeight` worked as it should. Thanks!
