### ISSUE TITLE
Improve typings for interpolations

### ISSUE THREAD

**Issue by stephenkoo** [emotion-js/emotion#735]
- `emotion` version: ^9.2.3
- `react` version: ^16.4.0

What you did:
```tsx
const aRandomValue = { value: 100 };

css({
  fontWeight: aRandomValue.value,
})
```

What happened:
Error: `Argument of type '{ fontWeight: number; }' is not assignable to parameter of type 'Interpolation'.
  Type '{ fontWeight: number; }' is not assignable to type 'ClassInterpolation'.`

Suggested solution:
Replicate [existing fix done by styled-components](https://github.com/styled-components/styled-components/pull/428)

**Comment by Ailrun** [comment]
@stephenkoo Thank you for reporting this!
However, as far as based on what I try, it works well. Could you give a reproducible environment?
https://codesandbox.io/s/pjv9jy72xj
As you can see in the above codesandbox, it works without an error.

And IMO, your suggestted solution link is unrelated with current topic, since it's about emitting new error not removing existing errors...

**Comment by stephenkoo** [comment]
@Ailrun Thanks for taking a look.
The errors are found in [line 30 & 32](https://gitlab.com/stephenkoo/kanso/blob/add-css-foundations/src/styles/typography/utils.styles.tsx).
The object in question is on [line 34 here](https://gitlab.com/stephenkoo/kanso/blob/add-css-foundations/src/styles/typography/variables.styles.tsx)

**Comment by Ailrun** [comment]
@stephenkoo You mean `yarn lint:ts`? There's no error with that command....

**Comment by Ailrun** [comment]
@stephenkoo 
I notice that the problem is from CSS type.
It's based on MDN. You can find a following description about `font-weight` in MDN.
> In earlier versions of the font-weight specification, the property accepts only keyword values and the numeric values 100, 200, 300, 400, 500, 600, 700, 800, and 900. CSS Fonts Level 4 extends the syntax to accept any number between 1 and 1000.

It means that your typing for `fontWeight` in `InterfaceTypeElementProperties` is broken one (according to CSS Level 3 or lower), so I think you should change the typing into something compatible with `FontWeightProperty` in following code.
```ts
import { FontWeightProperty } from 'csstype';
```

**Comment by stephenkoo** [comment]
And also, the fontWeight values I reference are 100, 300, 400, 500, 700, & 900, so it should be CSS3 compliant. Really odd if csstype doesn't recognise those values.

**Comment by Ailrun** [comment]
@stephenkoo I mean, your typing in `InterfaceTypeElementProperties` use `number`, instead of `100 | 200 | ...`. That typing is not compatible one.

**Comment by Ailrun** [comment]
I should move `CSSObject` to bottom of the typings... the error message is so hard to understand.

**Comment by stephenkoo** [comment]
`fontWeight` in `InterfaceTypeElementProperties` is `number` though...I must be misunderstanding something
![screen shot 2018-06-20 at 11 34 00 am](https://user-images.githubusercontent.com/18624246/41632584-f18f0dd6-747d-11e8-96c7-bb76a8042723.png)

**Comment by Ailrun** [comment]
@stephenkoo That's the problem. `fontWeight` should be of subtype of `"inherit" | "initial" | "revert" | "unset" | "bold" | "bolder" | "lighter" | "normal" | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900`, where `number` is clearly not.

**Comment by stephenkoo** [comment]
Ok, so if I understand correctly based on your explanation, I can't just use generic `textTransform: string` in `InterfaceTypeElementProperties` as well - it must conform to `csstype`.

Purely my fault for not making my `InterfaceTypeElementProperties` consistent with csstype and nothing to do with `emotion`.

Thanks for looking into this issue @Ailrun, appreciate it.
