### ISSUE TITLE
RFC: css prop specificity

### ISSUE THREAD

**Issue by mitchellhamilton** [emotion-js/emotion#753]
Currently, the className and the css prop are merged with the styles from the className taking precedence over the css prop styles.
<details>
<summary>Example of how it works right now</summary>

```jsx
let SomeComponent = ({ className }) => (
  <div
    css={{
      color: "hotpink"
    }}
    className={className}
  >
    some content
  </div>
);
// gets converted into something like this
let SomeComponent1 = ({ className }) => (
  <div
    className={cx(
      css({
        color: "hotpink"
      }),
      className
    )}
  >
    some content
  </div>
);
```
</details>

Originally, we didn't merge the css prop and the className styles so in most cases the css prop would take precedence(but it really depended on which css call was first)

Someone opened an issue about the css prop not taking precedence (#308) so we changed it so the className takes precedence

Some people wanting to change it so that the css prop takes precedence over className (#450, #451)

<details>
<summary>Example of what some people want to change it to</summary>

```jsx
let SomeComponent = ({ className }) => (
  <div
    css={{
      color: "hotpink"
    }}
    className={className}
  >
    some content
  </div>
);
// gets converted into something like this
let SomeComponent1 = ({ className }) => (
  <div
    className={cx(
      className,
      css({
        color: "hotpink"
      })
    )}
  >
    some content
  </div>
);
```
</details>

I'm opening this issue to see what people think should take precedence, especially in relation to the css prop in emotion@10 (#637)

---------------

In my option, the current way is really useful for creating reusable components that allow styles to be overridden by passing a className to the css prop like this.
```jsx
const MyCheckbox = props => (
  <input
    type="checkbox"
    css={{
      height: 40,
      width: 40,
      color: 'green'
    }}
    {...props}
  />
)
```
This also mirrors the way styles are merged in styled with the styles from the className prop taking precedence over styles from the styled call.

People seem to want this changed because having the css prop override the class name would make it more similar to the style prop.
> My opinion about this: we deviate in many ways from things in regular HTML/CSS such as using the order of class names for the order of composition rather than than the insertion order and I'd prefer to solve use cases rather than than do what HTML does just because it's what HTML does.

Deciding which should take precedence is especially important because to take advantage of the new SSR features and setting options via context in emotion@10, only using the css prop, Global component and the styled api will be required so there will be a lot more usage of the css prop.
> Note that you will still be able to use the current `emotion` API in v10, you just won't get all the new stuff

I'm also especially leaning towards the current behavior because when only using the native APIs in emotion@10(i.e. not the emotion package), I can't see how you would get a className without getting it from a parent component(which means it's probably intended for overriding styles) but I'd love to hear other people's opinions on this!

**Comment by Andarist** [comment]
At first I was also buffled by this, because `style` <-> `css` relates to each other really nicely - so I would expect `css` to be the most important thing (othen than `style`). Knowing how things work - that `css` is just a convenience prop that boils down to being just a `className` - it makes sense to me to keep current behaviour. Especially that we need things being overridable and the current behaviour allows for that.

**Comment by ChristopherBiscardi** [comment]
Knowing that it compiles to a className, I'd expect it to be prop ordering related in the same way two of the same prop would be.

```jsx
<Thing css={...} className={...}>
```
to be

```js
cx(
  css(...),
  className
)
```

and

```jsx
<Thing className={...} css={...}>
```
to be

```js
cx(
  className,
  css(...)
)
```

---

that means that we'd concat two props instead of replace the first with the last, which may be more or less of a difference than picking an ordering and sticking with it, but that would be my mental model walking in fresh. "last prop wins" applied to css specificity/className ordering.

I do think the "ordering swap" in the "what some people would like to change it to" section is more confusing than the behavior in the first code sample.

**Comment by Andarist** [comment]
We need to handle this at runtime though and while in most (every?) engine the iteration through object properties is stable/predictable it's not guaranteed by the spec (AFAIK) and either way would be really inconvenient to implement detecting this.

**Comment by Andarist** [comment]
Seems like this is no longer relevant in light of emotion@10 which simply doesn't handle className in any special way (when used without compat mode).
