### ISSUE TITLE
Way to disable hash in test environment?

### ISSUE THREAD

**Issue by huchenme** [emotion-js/emotion#870]
Would it be nice if we could disable hash className and only use the `label` in test environment?

**Comment by Andarist** [comment]
Closing because of the reasons mentioned in https://github.com/emotion-js/emotion/pull/871#issuecomment-423888107 . Have in mind that querying elements by their class names make your tests really coupled to your implementation and we discourage such practice. There are better ways of querying your elements in tests - take a look at https://testing-library.com/docs/guide-which-query
