### ISSUE TITLE
Here is emotion typescript plugin by leetcode-opensource

### ISSUE THREAD

**Issue by Brooooooklyn** [emotion-js/emotion#873]
We implement [emotion-ts-plugin](https://github.com/LeetCode-OpenSource/emotion-ts-plugin) so that we can use emotion with TypeScript.

This repo is in early development, so we may need help from emotion community😀

**Comment by Andarist** [comment]
I'm glad that you have implemented what solves your problems 👍 This might definitely be helpful for others, but because it is a community plugin and we have an official one for Babel it seems that we might not want to advertise yours in the documentation. Closing this issue as it's not actionable, hope you understand.

**Comment by Brooooooklyn** [comment]
In TypeScript community, many people are using TypeScript **without babel**. So they cannot get benefit from the official plugin.

**Comment by Andarist** [comment]
> In TypeScript community, many people are using TypeScript without babel. So they cannot get benefit from the official plugin.

Yeah, got it - it's a little bit of a duplicated effort for us though and we don't have time capacity to handle both compilers officially. We also consider setting up TS + Babel a viable option. Even if you want TS to transpile TS syntax - the output can be given to Babel for just this transformation, or multiple ones if needed. Babel just seems to have more useful plugins in general than TS, so often such setup might be beneficial and not only just for emotion's sake.
