### ISSUE TITLE
Is it possible to only apply `labelFormat` to `css` but not `styled`?

### ISSUE THREAD

**Issue by huchenme** [emotion-js/emotion#880]
if I have these settings in my `babel-plugin`

```
autoLabel: true,
labelFormat: '[filename]--[local]'
```

The generated classNames for styles work well, but for components created using `styled`, the displayName because undesired

**Filename.styles.js**

```
const TestComponent = styled.div`
  color: red;
`
```

and generated snapshot becomes

```
<Filename-styles--TestComponent>
...
</Filename-styles--TestComponent>
```

This is very long and undesired, is there any ways to disable this for snapshot name?

**Comment by Andarist** [comment]
I'm not entirely sure, but there is a chance that this was an issue in v9. If this still is an issue for you please respond back with a repro case prepared so I could take a look. Until then I'm going to close this because I'm trying to focus only on relevant issues and need to clean up the issue tracker for that.
